import mongoose from "mongoose";
import Ashram from "./models/ashram.js"; // adjust path

const seedAshrams = async () => {
  await mongoose.connect("replace_with_your_mongodb_connection_string");

  const ashrams = [
    {
      slNo: 1,
      name: "Mahesh B Kulkarni",
      ashramName: "Madhuvana Agro Forestry",
      address: "RS 7/4B, Guruvinahalli, Kundgol Taluk, Dharwad District, PIN-580024, IN",
      mobile: ["9901775644"],
      cropDiversity: "More than 55 types of agro forestry medicinal plants",
    },
    {
      slNo: 2,
      name: "Dr Sanjay and Dr Jyoti Sanjay Chandargimath",
      ashramName: "Sanjeevani Goukulashrm",
      address: "Alnavar District, Dharwad, Karnataka, India",
      mobile: ["9448348973", "6364631956"],
      cropDiversity: "25 ತರದ ಹಣ್ಣುಗಳು, 25 ತರದ ಹಸಿ ಕಾಯಿಪಲ್ಲೆ, ಹಾವು ಗಡ್ಡೆ ಗೆಣಸುಗಳು",
    },
    {
      slNo: 3,
      name: "Lakshmikanthappa",
      ashramName: "",
      address: "Honngondanahalli, Sira TQ, Tumakuru District",
      mobile: ["9844598705"],
      cropDiversity: "Food forest, organic vegetables",
    },
    {
      slNo: 4,
      name: "B Pradeep",
      ashramName: "",
      address: "S/o Basavaraju, Chikkabellavi, Bellavi Post, Tumkur",
      mobile: ["9513015051"],
      cropDiversity: "ವಿವಿಧ ಹಣ್ಣಿನ gidaglu",
    },
    {
      slNo: 5,
      name: "ರವಿ ಗಂಗಪ್ಪ ಕುರಬೆಟ",
      ashramName: "",
      address: "ಮುಖ್ಯ ಪೋಸ್ಟ ಮರಕುಂಬಿ, ತಾಲೂಕ್ ಸೌದತ್ತಿ, ಜಿಲ್ಲೆ ಬೆಳಗಾಂ",
      mobile: ["9902273538"],
      cropDiversity: "ಲಿಂಬು, ಕರಿಮೆವು, ಗೂಂಜಾಳ, ಕಬು, ಶೇಂಗಾ",
    },
    {
      slNo: 6,
      name: "Sunil M S",
      ashramName: "",
      address: "Tubagere, Doddaballapur",
      mobile: ["9886896969"],
      cropDiversity: "ತರಕಾರಿಗಳು, ಮಾವು, ಹುಣಸೆ, ಮಿಶ್ರ ಹಣ್ಣುಗಳು, ಶ್ರೀಗಂಧ, ಹೆಬೆವು, ನುಗ್ಗೆ, ಅಗಸೆ, Dalchinni etc.",
    },
    {
      slNo: 7,
      name: "ಬಸವರಾಜು N D",
      ashramName: "",
      address: "ಚಿಂದೇನಹಳ್ಳಿ ಗಡಿ, ಅರಸೀಕೆರೆ ತಾಲೂಕು, ಹಾಸನ ಜಿಲ್ಲೆ",
      mobile: ["9741415073"],
      cropDiversity: "80 varieties",
    },
    {
      slNo: 8,
      name: "ಧನ್ವಂತರಿ ಸಸ್ಯಕಾಶಿ",
      ashramName: "",
      address: "ಹೊನ್ನಗೊಂಡನಹಳ್ಳಿ, ಶಿರಾ ತಾಲೂಕು, ತುಮಕೂರು ಜಿಲ್ಲೆ, PIN 572137",
      mobile: ["9844598705"],
      cropDiversity: "5000 ಕ್ಕು ಹೆಚ್ಚಿನ ಮರಗಳು ಇವೆ",
    },
    {
      slNo: 9,
      name: "ಪರಶುರಾಮ್ ಎತ್ತಿನಗುಡ್ಡ",
      ashramName: "",
      address: "ಅಂಚೆ/ಊರು: ಸುಳಿಕಟ್ಟಿ, ತಾ:ಕಲಘಟಗಿ, ಜಿಲಾ:ಧಾರವಾಡ್",
      mobile: ["9449949699"],
      cropDiversity: "80 ಮಾವು, ಪೆರಾಲ್, ಬತ್ತ, ಸಾಮೆ, ಮಡಿಕೆ, ಹೆಸರು, ಜೋಳ, ತೊಗರಿ",
    },
    {
      slNo: 10,
      name: "ವೀರೇಶ. ಮನಗೂಳಿ",
      ashramName: "",
      address: "ಮನಗೂಳಿ ಗ್ರಾಮ 586122, ಬಸವನ ಬಾಗೇವಾಡಿ ತಾಲೂಕು, ವಿಜಯಪುರ ಜಿಲ್ಲೆ",
      mobile: ["9591436195"],
      cropDiversity: "ಕಬು, ಬಾಳೆ, ಗೋವಿನ, ಜೋಳ, ತೆಂಗು, ಮಾವು, ಚಿಕ್ಕು, ಸೀಬೆ, ಮಹಾಗನಿ, ರೇಷ್ಮೆ",
    },
    {
      slNo: 11,
      name: "ಮಹಾಂತೇಶ ಚಂದ್ರಯ್ಯ ಹಿರೇಮಠ್",
      ashramName: "",
      address: "At post ತುರಮರಿ, ತಾ ಕಿತ್ತೂರ, ಜಿ ಬೆಳಗಾವಿ",
      mobile: ["8722025555"],
      cropDiversity: "25 ಸಾವಿರ ಗಿಡ ಮರಗಳು, ಮಾವು ಕೃಷಿ, ಕಬು ಕೃಷಿ, 500 ಎಕರೆ ಕೆರೆ ಹೊಂದಿದೆ",
    },
    {
      slNo: 12,
      name: "ಭೃಂಗೇಶ್ ಸಂಗನಬಸವನ ದೊಡ್ಡಿ",
      ashramName: "",
      address: "",
      mobile: ["9980950575"],
      cropDiversity: "ಮಾವು, ತೆಂಗು, ಅಡಿಕೆ, ಹಲಸು, ಹುಣಸೆ, ನಿಂಬೆ, ಮೂಸಂಬಿ, ಕಿತ್ತಳಿ, ಚಕೋತ, ಬಾಳೆ, ನೀರುಸೇಬು, ದಾಳಿಂಬೆ, ಬರ್ ಆಪಲ್, ಸೀಬೆ ಹಣ್ಣು, ನೆಲ್ಲಿಕಾಯಿ, ಹತ್ತಿ ಹಣ್ಣು, ಸೀತಾ ಪಲ, ರಾಮ ಪಲ, ಲಕ್ಷಣ ಪಲ, ಶ್ರೀಗಂಧ, ತೇಗ, ನೇರಳೆ, ಬೇವು ಮರ, ಹೆಬೆವು ಇತರೆ",
    },
    {
      slNo: 13,
      name: "Raviteja Km",
      ashramName: "",
      address: "79/6 Kunabevu, ಚಿತ್ರದುಗ",
      mobile: ["9844166655"],
      cropDiversity: "ಸಮಗ್ರ ಕೃಷಿ, ಮೇವಿನ ಬೆಳೆ, ವಾಣಿಜ್ಯ ಬೆಳೆ, ಅರಣ್ಯ ಬೆಳೆ",
    },
    {
      slNo: 14,
      name: "ಶಿವಣ್ಣ. ಏನ್",
      ashramName: "",
      address: "ಶಿವಪುರ, ಅರೂಡಿ, ದೊಡ್ಡಬಳ್ಳಾಪುರ ತಾಲೂಕು, ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ ಜಿಲ್ಲೆ 561204",
      mobile: ["9880501520"],
      cropDiversity: "ಅಡಿಕೆ, ಏಲಕ್ಕಿ, ಬಾಳೆ, ಕೊಕೊ, ನುಗ್ಗೆ, ನಿಂಬೆ, ಏಲಕ್ಕಿ, ತೆಂಗು, ಬಟರ್ ಫ್ರಟ್, ಅರಿಶಿನ, ಬೇಲದ ಹಣ್ಣು",
    },
    {
      slNo: 15,
      name: "Rajeshwari Alur",
      ashramName: "ALUR FARM",
      address: "Anagodu",
      mobile: ["9964596246"],
      cropDiversity: "Coconut main crop, Turmeric, Mara genasu, sweet potatoes, papaya, banana, mango, jack fruits, etc",
    },
    {
      slNo: 16,
      name: "Raveesha S K",
      ashramName: "",
      address: "Sannenahalli, Tiptur TQ, Tumkur Dist",
      mobile: ["7892655814"],
      cropDiversity: "Coconut fruit",
    },
    {
      slNo: 17,
      name: "Suryakant B. NAIK",
      ashramName: "Shree Veerashiv Vidya Samsthe",
      address: "Kochari, ta.Hukkeri, Belgavi, Karnataka",
      mobile: ["9448693001"],
      cropDiversity: "ದೇಸಿ ಬಾಳೆ ತೋಟ, ಕಬಿನ ತೋಟ, ಚಿಕ್ಕು, ಮತ್ತು ತೆಂಗಿನ ತೋಟ, ಇನ್ನಿತರ ದ್ವಿದಳ ಬೆಳೆ",
    },
    {
      slNo: 18,
      name: "ಈರಣ್ಣ ಯಲ್ಲಪ್ಪ ಬಾರಕೇರ",
      ashramName: "",
      address: "ಗ್ರಾಮ: ಮಡ್ಲಿಶಿಗ್ಗಾವಿ, ತಾಲೂಕು ಹಾವೇರಿ, ಜಿಲ್ಲೆ",
      mobile: ["9902981651"],
      cropDiversity: "ದೇಶಿ ತಳಿಯ ಸಿರಿದಾನ್ಯಗಳು, ತರಕಾರಿ, ಬೇಳೆ, ಕಾಳುಗಳು ಇನ್ನು ಮುಂತಾದವವು",
    },
    {
      slNo: 19,
      name: "Ammana prakruti madilu",
      ashramName: "Ammana prakruthi madilu",
      address: "Mannina mane, Ammanaghatta, Gubbi TQ, Tumkur dist 572216",
      mobile: ["9108907673"],
      cropDiversity: "Coconut, arecanut, black pepper, papaya, custard apple, jamun, lemon, mango, guava, sweet orange, tamarind, coffee, cardamom, jackfruit, multivitamin, laksham phal, paneer, glyricedia, pueraria, banana, and medicinal plants",
    },
    {
      slNo: 20,
      name: "Arjun R Sulibhavimath",
      ashramName: "",
      address: "K Hunashikatti, taluk kundgoal, Dharwad",
      mobile: ["9680499656", "8553600000"],
      cropDiversity: "Areca plants, forest plants, fruits, many variety plants",
    },
    {
      slNo: 21,
      name: "ತಾರಾನಾಥ್ ಉಮ",
      ashramName: "ಶ್ರೀ ಗುರುಶಾಂತಿ ಧಾಮ ಧರ್ಮದತ್ತಿ",
      address: "ಯಗಟಿಪುರ, ಯಗಟಿ ಹೋಬಳಿ, ಕಡೂರು, ಚಿಕ್ಕಮಗಳೂರು 577140",
      mobile: ["9845941118"],
      cropDiversity: "ತರಕಾರಿ, ಅರಿಶಿಣ, ತೆಂಗು, ಅಡಿಕೆ, ಹಣುಗಳು",
    },
    {
      slNo: 22,
      name: "ಮಂಜುನಾಥ ಬಳೊಳ್ಳಿ",
      ashramName: "ಶಿವನಂದಿ ನ್ಯಾಚುರಲ್ ಫಾಮ್",
      address: "ಸಾಯಿ ಫಂಕ್ಷನ್ ಹಾಲ್ ಪಕ್ಕದಲ್ಲಿ, ಗೌರಿಪುರ ರಸ್ತೆ, ಕನಕಗಿರಿ, ಕೊಪ್ಪಳ ಜಿಲ್ಲೆ",
      mobile: ["9916007262"],
      cropDiversity: "ರೇಷ್ಮೆ, ದಾಳಿಂಬೆ, ಕಾಗಜಿ ನಿಂಬೆ, ನುಗ್ಗೇಕಾಗಿ, ಪೇರಲ, ಸೀತಾಫಲ, ದುಂಡಮಲ್ಲಿಗೆ",
    },
    {
      slNo: 23,
      name: "PRAKASH R, ಪ್ರಕಾಶ್ ಆರ್",
      ashramName: "",
      address: "S/RUDRAPPA ND, NERLIGE VILLAGE, DAVANGERE TQ AND DIST",
      mobile: ["9986451541"],
      cropDiversity: "ತೆಂಗು, ಅಡಿಕೆ, ಬಾಳೆ, ಪಪ್ಪಾಯಿ, ರಾಮ ಫಲ, ಲಕ್ಷಣ ಫಲ, ಸೀತಾಫಲ, ಲವಂಗ, ಕಾಳು ಮೆಣಸು, ಮತ್ತು ವಿವಿಧ ರೀತಿಯ ತರಕಾರಿ, ಗೆಡ್ಡೆ ಗೆಣಸು",
    },
    {
      slNo: 24,
      name: "ಸುರೇಂದ್ರ ಸುಂದರವನ",
      ashramName: "ಸುಂದರವನ",
      address: "ನಿಜಿಯಪ್ಪನದೂಡಿ, ಕೂಟಗಲ್ ಹೋಬಳಿ, ರಾಮನಗರದ ತಾಲೂಕು, ಜಿಲ್ಲೆ, PIN 562159",
      mobile: ["9980807024"],
      cropDiversity: "ತರಕಾರಿ, ಮಾವು, ತೆಂಗು, ಔಷಧಿ ಸಸ್ಯಗಳು, ಅರಣ್ಯ ಕೃಷಿ, ಹಣ್ಣೆನ ಗಿಡಗಳು, ನಸರಿ, ಹಾಗೂ ಇತರೇ ಗಿಡಗಳು",
    },
    {
      slNo: 25,
      name: "ಸುಲೋಚನಾ ಸಜ್ಜನ್ ಕೃಷಿ ಆಶ್ರಮ",
      ashramName: "ಸುಲೋಚನಾ ಸಜ್ಜನ್ ಕೃಷಿ ಆಶ್ರಮ",
      address: "ಹುಲಿಕೆರೆ, ಕೂಡ್ಲಿಗಿ ತಾಲೂಕು, ವಿಜಯನಗರ ಜಿಲ್ಲೆ",
      mobile: ["9902661597"],
      cropDiversity: "ಸಮಗ್ರ ಕೃಷಿ, ಹಣ್ಣಿನ ಮರಗಳು, ನಿರಂತರ ಆದಾಯ ತರುವ ಬೆಳೆಗಳು",
    },
    {
      slNo: 26,
      name: "Nagaraja Galeppa",
      ashramName: "",
      address: "Anekal, Hagaribommanahalli tq, Vijayanagara dist",
      mobile: ["9901491018"],
      cropDiversity: "100 coconut, mahogony, All forest varieties and fruits",
    },
    {
      slNo: 27,
      name: "ಸಾಯಿರಾಮ ರೆಡ್ಡಿ",
      ashramName: "",
      address: "ಮರಳೇನಹಳ್ಳಿ, ದೊಡ್ಡಬಳ್ಳಾಪುರ, ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ ಜಿಲ್ಲೆ",
      mobile: ["9242950017"],
      cropDiversity: "ಮಾವು, ಬಾಳೆ, ಹಲಸು, ಕಾಫಿ, ಸಪೋಟ, ಅಡಿಕೆ, ಚಕೋತ, ಸೀಬೆ ಮುಂತಾದವು",
    },
    {
      slNo: 28,
      name: "M D ತಿಪ್ಪೇಸ್ವಾಮಿ",
      ashramName: "",
      address: "ದೇವರಮರಿಕುಂಟೆ, ಚಳ್ಳಕೆರೆ ತಾಲೂಕು, ಚಿತ್ರದುಗ ಜಿಲ್ಲೆ",
      mobile: ["7259377737"],
      cropDiversity: "ಮಾಡಬೇಕು",
    },
    {
      slNo: 29,
      name: "Shobha B Abbigeri",
      ashramName: "",
      address: "Bhimaraddi I Abbigeri, Madli, Taluq: Shiggaon, District: Haveri",
      mobile: ["9663230036"],
      cropDiversity: "Tengu, adike, godambi, perala, chikku, mavu, mallige, rose, dasavala etc, maragenasu, sihigenasu, tulasi, aloevera, nugge, lemon, lemongrass, ondelaga, chogachi, kumbala",
    },
    {
      slNo: 30,
      name: "ಚಂದ್ರಶೇಖರ್ ರೆಡ್ಡಿ",
      ashramName: "ಪುಣ್ಯಕೋಟಿ ಫಾಮ (ರೆಡ್ಡಿ ಫಾಮ)",
      address: "ಮನಗೂಳಿ ಪಟ್ಟಣ, ಬಸವನ ಬಾಗೇವಾಡಿ ತಾಲೂಕು, ವಿಜಯಪುರ ಜಿಲ್ಲೆ",
      mobile: ["7204131659"],
      cropDiversity: "ಎಲ್ಲಾ ತರಹದ ತೋಟಗಾರಿಕಾ ಬೆಳೆಗಳು, ಮೇವಿನ ಬೆಳೆಗಳು, ಕಬು ಇತರೆ",
    },
    {
      slNo: 31,
      name: "Naveen Kumar H R",
      ashramName: "",
      address: "#119/2, behind Adaganahalli govt School, Byadarahalli post, Hebbal Hobli, K R Nagar, Pin code-571602",
      mobile: ["9945811771"],
      cropDiversity: "We have lot of Trees, Fruits, Areca, Medicinal Plants, Creepers",
    },
    {
      slNo: 32,
      name: "Aswath Reddy T",
      ashramName: "Aswath Reddy krushi Ashrama",
      address: "Ankarhatti Village, Sugatur Hobli, Kolar Taluk, Kolar District -563126",
      mobile: ["9741278742"],
      cropDiversity: "All Types of fruits plants available",
    },
    {
      slNo: 33,
      name: "ಹರಿಕೃಷ್ಣ ಕಾಮತ್",
      ashramName: "ಮಂಜುನಾಥ ಸಾವಯವ ಕೃಷಿ ಸೇವಾ ಆಶ್ರಮ",
      address: "ದುಗಾಗಿರಿ, ಪುತ್ತೂರು",
      mobile: ["9481390710"],
      cropDiversity: "ಗೆಡ್ಡೆ - ಗೆಣಸು, ಸೊಪ್ಪು ತರಕಾರಿಗಳು, ಔಷಧಿಯ ಸಸ್ಯಗಳು, ಹಣ್ಣಿನ ಸಸ್ಯಗಳು",
    },
    {
      slNo: 34,
      name: "Kundaranahalli Ramesh",
      ashramName: "",
      address: "Shakthibhavana 1 St Main, Jayanagar east, Tumakuru 572102",
      mobile: ["9886774477"],
      cropDiversity: "1008 species plan at present morethan 400 species",
    },
    {
      slNo: 35,
      name: "ಎಸ್ ಎಂ ವೆಂಕಟೇಶ್",
      ashramName: "",
      address: "Krushi nilaya park road near Lakshmi clinic, kuvempunagar, tumkur 572103",
      mobile: ["9448550974"],
      cropDiversity: "ಮುಖ್ಯ ಬೆಳೆ ಅಡಿಕೆ, ತೆಂಗು, ಬಾಳೆ, ಬಟರ್ ಫ್ರಟ್, ಪಪ್ಪಾಯ, ಮಾವು, ಕಾಳುಮೆಣಸು, ಕಾಫಿ, ಸುವರ್ಣಗೆದ್ದೆ ಇತ್ಯಾದಿ",
    },
    {
      slNo: 36,
      name: "Raghavendra Bhat",
      ashramName: "Chiguru Farm",
      address: "Therubeedi Village, Harohalli Taluk, Ramanagara District",
      mobile: ["9845258575"],
      cropDiversity: "Self sustaining farm growing varieties of fruits and all kinds of grains (rice, ragi, millets) and pulses (tur, urad, moong etc)",
    },
    {
      slNo: 37,
      name: "Vijayakumar B S",
      ashramName: "",
      address: "Davanagere",
      mobile: ["9342131318"],
      cropDiversity: "ನುಗ್ಗೆ, ತೆಂಗು, ಮಾವು, ಹಲಸು, ನೇರಳೆ, ನೆಲ್ಲಿಕಾಯಿ, ಸಪೋಟ, ಮೋಸಂಬಿ, ಕಿತ್ತಳೆ, ಗೋಡಂಬಿ, ಚರ್ರಿ, ಅಂಜೂರ",
    },
    {
      slNo: 38,
      name: "Rudranna Gulaguli",
      ashramName: "",
      address: "Aditya Nagar, Near Anjuman College, Gadag 582103",
      mobile: ["8867237374"],
      cropDiversity: "Mango, Sitaphal, Coconut, Chikku, Nimbu, Drumstick, Cashew, Teak, Hebbevu, Turmeric, Banana",
    },
    {
      slNo: 39,
      name: "ಕೇಶವಮೂರ್ತಿ ಜಿ",
      ashramName: "",
      address: "ಪಿ ಚಳಗೇರಿ, ಅರೆಮಲ್ಲಾಪುರ ರಸ್ತೆ",
      mobile: ["9611611577"],
      cropDiversity: "ತೆಂಗು, ಮಾವು, ಹಲಸು, ನೇರಳೆ, ಪೇರಲ, ಬೇಲ ಇನ್ನೂ ಸುಮಾರು 30 ಜಾತಿಯ ಹಣ್ಣಿನ ಗಿಡಗಳು",
    },
    {
      slNo: 40,
      name: "Shilpa D",
      ashramName: "Krushi dairy farm",
      address: "Pharamanahalli village",
      mobile: ["9686236202"],
      cropDiversity: "Banana, drumsticks, curry leaves, papaya, mulberry",
    },
    {
      slNo: 41,
      name: "Ramesh Kumar B",
      ashramName: "",
      address: "#261/3, 1st cross, kaggadasapura, c v Raman Nagar post, Bengaluru 560 093",
      mobile: ["9845335725"],
      cropDiversity: "Horticulture",
    },
    {
      slNo: 42,
      name: "ರಾಜೀವ ರಂಗನಾಥ ಹೆಬಸೂರ",
      ashramName: "",
      address: "೨೪೪, ತೋಟದ ಮನೆ, ಮು, ಯಕ್ಕೇರಿ, ಪೊ, ಮುನವಳ್ಳಿ, ತಾ, ಸವದತ್ತಿ ಎಲ್ಲಮ್ಮ, ಜಿ, ಬೆಳಗಾವಿ, ೫೯೧೧೧೭",
      mobile: ["9731324323"],
      cropDiversity: "ಬಾಳೆ, ನುಗ್ಗೆ, ಮಾವು, ತೆಂಗು, ಪೇರಲೆ, ಇತ್ಯಾದಿ",
    },
    {
      slNo: 43,
      name: "ಶರತ್ ಕುಮಾರ್ ಬಾಬಾ ಗೌಡ್ ಪಾಟೀಲ್",
      ashramName: "",
      address: "ಸಾಕಿನ ಸಾಲೇಟೋಗಿ ತಾಲೂಕ ಇಂಡಿ ಜಿಲಾ ವಿಜಯಪುರ",
      mobile: ["9880854262"],
      cropDiversity: "ಕಬು, ಬಾಳೆ, ಲಿಂಬೆ, ನುಗ್ಗೆ, ಹತ್ತಿ, ಜೋಳ, ಕಡಲೆ, ತೊಗರೆ, ತರಕಾರಿ, ಮಾವು, ಪಪ್ಪಾಯಿ, ದನದ ಮೇವು, ತೊಗರಿ, ಹುರಳೆ, ಅಲಸಂದೆ, ಜೋಳ",
    },
    {
      slNo: 44,
      name: "ಶ್ರೀ ಹನಮಂತಪ್ಪ G ಚಿಂಚಲಿ",
      ashramName: "",
      address: "ಸಾ/ಮಾಢಳ್ಳಿ ತಾಲೂಕು, ಲೇಶ್ವರ ಜಿಲ್ಲೆ, ಗದಗ",
      mobile: ["9945788923"],
      cropDiversity: "ನೈಸಗಿಕವಾಗಿ ಬೆಳೆದ ಎಲ್ಲ ಬೆಳೆಗಳು",
    },
    {
      slNo: 45,
      name: "Mohan Kumar b s",
      ashramName: "",
      address: "S/o shankaralingaiah b, Beerasandra at post, Tiptur taluk, Tumkur district, Pin code 572114",
      mobile: ["8217432873"],
      cropDiversity: "Coconut, arecanut, Banana, mango, jackfruit, cardamom, orange, butter fruit, and guava",
    },
    {
      slNo: 46,
      name: "Abhishek R",
      ashramName: "",
      address: "40/2 Ajapanahalli, Swandenahalli post, Tumkur",
      mobile: ["9731733011"],
      cropDiversity: "Coconut, Mango and others",
    },
    {
      slNo: 47,
      name: "BHIMASHANKAR BASAPPA HUGAR",
      ashramName: "",
      address: "Indi",
      mobile: ["8867252006"],
      cropDiversity: "Red Gram, millet",
    },
    {
      slNo: 48,
      name: "ಅಕ್ಕಮಹಾದೇವಿ ದೊಡ್ಡನಗೌಡ ಪಾಟೀಲ್",
      ashramName: "",
      address: "೧೬೦/ಅ, ಸಜ್ಜಲಶ್ರೀ ಬಿಲ್ಡಿಂಗ್, ಬಸವನಗರ, ಇಳಕಲ್",
      mobile: ["9380361910"],
      cropDiversity: "ಎಲ್ಲ ತರಹದ ಹಣ್ಣುಗಳು, ತರಕಾರಿ",
    },
    {
      slNo: 49,
      name: "Irappa sannahanmantappa bandi",
      ashramName: "",
      address: "Kodihal, tq.-ilkal, dt-bagalakote",
      mobile: ["9945381852"],
      cropDiversity: "ಮಾವು, ಚಿಕ್ಕು, ಪೇರಳೆ, ಸೀತಾಫಲ, ನುಗ್ಗೆ",
    },
    {
      slNo: 50,
      name: "ಮೋಹನ್ ಕುಮಾರ್ ಬಿ ಸಿ",
      ashramName: "",
      address: "ಅತ್ತಿಗುಪ್ಪೆ, ಹುಣಸೂರು ತಾಲೂಕು, ಮೈಸೂರು ಜಿಲ್ಲೆ",
      mobile: ["9448780828"],
      cropDiversity: "ತೆಂಗು, ಮಾವು, ತೇಗ, ಹಲಸು",
    },
    {
      slNo: 51,
      name: "ಜಯಪ್ರಕಾಶ್ ಟಿ, ಜೆ",
      ashramName: "",
      address: "#1126, ನಿಜಲಿಂಗಪ್ಪ ಬಡಾವಣೆ, ದಾವಣಗೆರೆ",
      mobile: ["9448313335", "9008400000"],
      cropDiversity: "ಸಿರಿದಾನ್ಯಗಳು, ತರಕಾರಿ, ಮೆಕ್ಕೆ ಜೋಳ",
    },
    {
      slNo: 52,
      name: "ನಿಸರ್ಗಧಾಮ್ ಕೃಷಿ ಆಶ್ರಮ",
      ashramName: "ನಿಸರ್ಗಧಾಮ್ ಕೃಷಿ ಆಶ್ರಮ",
      address: "At/Post: Bellad Bagewadi, Tq: Hukkeri, Dist: Belagavi, Pin: 591305",
      mobile: ["8904108936", "9448875212"],
      cropDiversity: "ಸಮ್ಮಿಶ್ರ, ತೆಂಗು, ಮಾವು, ಚಿಕು, ವಾಟರ್ ಆಪಲ್, ಸೀತಾಫಲ, ರಾಮ ಫಲ, ಹನುಮ ಫಲ, ಲಕ್ಷ್ಮಣ್ ಫಲ, ಬೇಲದ ಹಣ್ಣು, ಹಲಸಿನ ಗಿಡ, ಸೇಬು, ಲಿಂಬೆ ಹಣ್ಣು, ಪೆರು, ಡಾಳಿಂಬೆ ಮುಂತಾದ",
    },
    {
      slNo: 53,
      name: "ರಾಜೇಶ್ ಎಸ್. ಪಿ.",
      ashramName: "",
      address: "#305, ಶ್ರೀಗಂಧ, 9ನೇ ಮುಖ್ಯ ರಸ್ತೆ, ರೈಲ್ವೆ ಮೆನ್ಸ್ ಲೇಔಟ್, 2ನೇ ಹಂತ, ಬೆಂಗಳೂರು -560110",
      mobile: ["9845979139"],
      cropDiversity: "ಅಡಿಕೆ, ತೆಂಗು, ಮಾವು, ಸಪೋಟ ಇನ್ನೂ ಹಲವಾರು ಹಣ್ಣುಗಳು",
    },
    {
      slNo: 54,
      name: "B RadhaKrishna & Sandya Rani",
      ashramName: "",
      address: "Konasale - Village, Madduru -Taluk, Mandya- Dist",
      mobile: ["9902010769"],
      cropDiversity: "Biodiversity is created, Holistic Agriculture",
    },
    {
      slNo: 55,
      name: "Kiran M.S",
      ashramName: "Siri Farm",
      address: "Taraganahalli Grama, Hulahalli Hobli, Nanjanagud Taluk, Mysuru",
      mobile: ["9740277877"],
      cropDiversity: "Border Agro-forestry plants, Fruit plantations, Coconut plantations - all being grown without any chemicals and pesticides",
    },
    {
      slNo: 56,
      name: "Sampath kumar p",
      ashramName: "",
      address: "Kebbepura nitre post, chamarajanagar tq and district",
      mobile: ["8088053074", "9448124739"],
      cropDiversity: "Coconut, Areca, guava, sapota, nerale, banana, turmeric, ginger, garlic, onion, drumstick, Agashe",
    },
    {
      slNo: 57,
      name: "ಆಶಾ ಕಂಠಿ",
      ashramName: "",
      address: "Greeshma, 145/2A, Maka Layout, Jewargi Colony, Kalaburagi - 585102",
      mobile: ["9844270232"],
      cropDiversity: "ತೊಗರಿ, ಜೋಳ, ಚಿಲ್ಲಿ ಬೀಜ",
    },
    {
      slNo: 58,
      name: "H M Puttaswamy Gowda",
      ashramName: "",
      address: "Halli Gadde, Igoor Post, Sakleshpur -Taluk, Hasan District",
      mobile: ["9448032961"],
      cropDiversity: "coffee, cardamom, and areca",
    },
    {
      slNo: 59,
      name: "ಶಿವಾನಂದ ಕಟ್ಟಿಕರ",
      ashramName: "",
      address: "ಮೋಳೆ, ತಾ/ಕಾಗವಾಡ, ಜಿ/ಬೆಳಗಾವಿ",
      mobile: ["9108808856"],
      cropDiversity: "ಕಬು, ಮೆಕ್ಕೆ ಜೋಳ, ಕಡಲೆ, ಗೋಧಿ",
    },
    {
      slNo: 60,
      name: "Malleshappa Bisirotti",
      ashramName: "",
      address: "Hregunjala -Village and Panchayat, Kundagola -Taluk, Dharawad -Dist",
      mobile: ["9945011754"],
      cropDiversity: "All Variety dry crops",
    },
    {
      slNo: 61,
      name: "Nethravathi",
      ashramName: "",
      address: "No,753, smv layout, nagarbhavi, bangalore-560091",
      mobile: ["9741066522"],
      cropDiversity: "Fruits and medicinal plants",
    },
    {
      slNo: 62,
      name: "ಜೋಸೆಫ್ ಬಾರೆಟ್ಟೋ",
      ashramName: "ಈಡನ್ ಗಾಡನ್",
      address: "ಕೊಳಗಾವೆ ಗ್ರಾಮ, ಜಾಗರ ಅಂಚೆ ಮತ್ತು ಹೋಬಳಿ, ಚಿಕ್ಕಮಗಳೂರು ತಾಲೂಕು ಮತ್ತು ಜಿಲ್ಲೆ",
      mobile: ["9448530202"],
      cropDiversity: "ಕಾಫಿ, ಅಡಿಕೆ, ಕರಿ ಮೆಣಸು, ಏಲಕ್ಕಿ",
    },
    {
      slNo: 63,
      name: "ಡಾ. ನಿಮಲ ಕೆಳಮನಿ",
      ashramName: "ರಜತಗಿರಿ",
      address: "",
      mobile: ["9482455038"],
      cropDiversity: "150 species",
    },
    {
      slNo: 64,
      name: "ವಿನಯ್ ಸೊಕ್ಕೆ",
      ashramName: "",
      address: "Sokke, Ajjampura, Chikmagalure",
      mobile: ["8792559219", "8050998779"],
      cropDiversity: "ಇಲ್ಲ",
    },
    {
      slNo: 65,
      name: "ಡಾ.ರಾಜೇಂದ್ರ ಯರನಾಳೆ",
      ashramName: "ಸಾಂಸ್ಕೃತಿಕ ಲೋಕ",
      address: "ಕಲುಗಿನ ಕಟ್ಟೆ, ಕಲಘಟಗಿ ಹೆದ್ದಾರಿ, ನಾವದಗಿ(ಬಿ.), ತಾ.ಕಮಲಾಪುರ, ಜಿ.ಕಲುಗಿ -585313",
      mobile: ["9632561135"],
      cropDiversity: "ಪೇರು, ಶ್ರೀಗಂಧ, ನೇರಳೆ, ನೆಲ್ಲಿ, 80 ಪ್ರಕಾರದ ಮರಗಳು",
    },
    {
      slNo: 66,
      name: "ದೊಡ್ಮನೆನಿ ವಾಣಪ್ಪ",
      ashramName: "",
      address: "S/o ಮರುಳಪ್ಪ ರಾಂಪುರ, ರಾಂಪುರ ಅಂಚೆ, ಕಣಕಟ್ಟೆ ಹೋಬಳಿ, ಅರಸೀಕೆರೆ ತಾಲೂಕ್, ಹಾಸನ ಜಿಲ್ಲೆ, 573126",
      mobile: ["9483783119", "9449338315"],
      cropDiversity: "ಮಾವು, ಹಲಸು, ನೇರಳೆ, ಸೆಬೆ, ಸೇಬು, ಕಿತ್ತಳೆ, ಪುಟ್ಟ ಬಲೆ, ಸಪೋಟ, ನುಗ್ಗೆ, ಕರಿಬಾವು, ತೆಂಗು, ಅಡಿಕೆ, ಸಾಬೇರಿ, ಚೆರ್ರಿ",
    },
    {
      slNo: 67,
      name: "Deekshith kumar SN",
      ashramName: "SCN model farm",
      address: "sy no. 68 singena Agrahara, Anekal taluk, bengaluru 560099",
      mobile: ["9035159526"],
      cropDiversity: "Jackfruit, mango, guava, papaya, banana, vegetables, spinach, oyster and Milky mushroom, micro greens etc",
    },
    {
      slNo: 68,
      name: "ಸಂತೋಷ ಬಸವರಾಜು",
      ashramName: "ನೆರಳು ನ್ಯಾಚುರಲ್ಸ",
      address: "91/1, ಯೆರಿಯೂರ್ ಗ್ರಾಮ, ತೆರಕಾನಂಬಿ ಹೋಬಳಿ, ಗುಂಡ್ಲುಪೇಟೆ ತಾ",
      mobile: ["8310587694"],
      cropDiversity: "Tapasi, Nalli, Surinam cherry, Barbados cherry, Karonda, Seethaphala, Lakshamaphala, Ramaphala, Banana, Java Apple, Pappaya, Moringa, Nerale, Mango, Halasu, Godambi, Sapota, Water apple, Noni, Seebe, Dalimbe, Butter fruit, Star fruit, Wild mango, Curry leaves, Turmeric, Rudrakshi, Antuvala, Honge, Hippu Nerale, Sampige, Simaruba, Bamboo, Basavana paada, Nilgiri, Neem, Matti, Teak, Baage, Muttuga, Kaadu badami, Aadusoge, ಅಡಿಕೆ, Silkcotton tree, Kaadu basale",
    },
    {
      slNo: 69,
      name: "ಶಿವರಾಜಕುಮಾರ ಎನ್ ಹಳ್ಳಿ",
      ashramName: "ಶಿವನಂದಿ ಕೃಷಿ ಆಶ್ರಮ",
      address: "ಗರೂರ(ಬಿ) ಗ್ರಾಮ, ತಾ: ಜಿಲಾ ಕಲಬುರಗಿ ೫೮೫೨೬೫",
      mobile: ["8095007278"],
      cropDiversity: "ತೊಗರಿ, ಕಬು, ಇರುಳಿ, ಅಲಸಂದಿ",
    },
    {
      slNo: 70,
      name: "Nanda Ramesh Bhairikoppa",
      ashramName: "",
      address: "Khalsa hunasikatti, Taluka kalaghatagi, districte Dharavada",
      mobile: ["9845185673"],
      cropDiversity: "Maige",
    },
    {
      slNo: 71,
      name: "M S Manjegowda",
      ashramName: "",
      address: "#1028/1C, GF-102 Lakshmi Ramaswamy Soudha, Jayalakshmi vilas Road, Chamarajapuram, Mysore 570005",
      mobile: ["9916909663"],
      cropDiversity: "Coconut and Areca",
    },
    {
      slNo: 72,
      name: "Arun M",
      ashramName: "",
      address: "#5, 1st main, 6th cross, lokanayaka nagara, metagalli post, mysuru -16",
      mobile: ["9341920508"],
      cropDiversity: "Coconut -15, Arecanut -120, Jackfruit -12, Star fruit- 2, Mahogany -20, Hebbevu -30, Teak 5, honne-2, beete -2, sandalwood -5, neem- 5, pomegranate- 2, guva -10, Drumstick -10, sesbania-12, drumstick-10, wood apple-2, Mango- 10, paneer apple -2, waterapple -1, Gooseberry-2, Butterfruit 20, Banana 50, papaya 50, Chikku 5, rambuthan -2, mangosteen -1, cherry",
    },
    {
      slNo: 73,
      name: "S.T. Patil",
      ashramName: "",
      address: "Same as above",
      mobile: ["9880854262"],
      cropDiversity: "Vegetable, Jower, Medicinal Plants, variety of tree",
    },
    {
      slNo: 74,
      name: "ಸಂಗಮೇಶ ವಿಜಾಪುರ",
      ashramName: "",
      address: "ಮುಳವಾಡ, ವಿಜಯಪುರ ಜಿಲ್ಲೆ",
      mobile: ["9741362217"],
      cropDiversity: "ಪೇರು, ಮಾವು, ಚಿಕ್ಕು, ನೇರಳೆ, ವಾಟರ್ ಆಪಲ್, ಬೆಟ್ಟದ ನೆಲ್ಲಿ, ಬಾಳೆ, ಮಹಾಘನಿ, ಶ್ರೀಗಂದ, ರಕ್ತ ಚಂದನ ಇತರೆ",
    },
    {
      slNo: 75,
      name: "Ravikumar B",
      ashramName: "",
      address: "S/o B Malleshappa",
      mobile: ["9986711975"],
      cropDiversity: "Papaya, Fig, Guava, fruits, vegetables",
    },
    {
      slNo: 76,
      name: "Veereshwara.M",
      ashramName: "",
      address: "Mallikarjuna boys PG, anjaneya badavane 5th cross, BIET Collage main road near hemavathi hostel, davanagere -577004",
      mobile: ["9902021464"],
      cropDiversity: "Areca, Coconut, Pappaya",
    },
    {
      slNo: 77,
      name: "ಆನಂದ ಕೋಟಿ",
      ashramName: "",
      address: "ತುಮರಿಕೊಪ್ಪ ಗ್ರಾಮ, ಹೀರೆಹುಳ್ಳಾಳ (ಪೋಸ್ಟ), ಹಾನಗಲ್ಲ ತಾಲೂಕು, ಹಾವೇರಿ ಜಿಲ್ಲೆ 581148",
      mobile: ["6363544894"],
      cropDiversity: "ಮಳೆ ಆಶ್ರಿತ ಮೆಕ್ಕೆ ಜೋಳ, ತೊಗರಿ, (ಬದುವಿನಲ್ಲಿ), ಹತ್ತಿ, ಭತ್ತ (ನ ಪಡೆದ ನಂತರ ಮುಂದೆ ತೋಟ ಮತ್ತು ತೋಟಗಾರಿಕೆ ಬೆಳೆಗಳನ್ನು ಬೆಳೆಯಲು ಪ್ರಾರಂಭಿಸಬೇಕು)",
    },
    {
      slNo: 78,
      name: "ಗಂಗಯ್ಯ ಈರಯ್ಯ ಖಾನಾಪುರಮಠ",
      ashramName: "",
      address: "ಗಂಗಯ್ಯ ಈರಯ್ಯ ಖಾನಾಪುರಮಠ",
      mobile: ["9740272924"],
      cropDiversity: "ಹಣ್ಣು, ತರಕಾರಿ, ಕಾಲುಗಳು",
    },
    {
      slNo: 79,
      name: "Shivu",
      ashramName: "",
      address: "#43 Aralalusandra village, Thungani post, Kasabha ho, kanakapura taluk, Ramanagara district",
      mobile: ["9591948756"],
      cropDiversity: "Mango, coconut, nimbu, vegetable, ragi, some medicinal plants, teakwood, mahagani, etc",
    },
    {
      slNo: 80,
      name: "Jasti Jagan Mohan Rao",
      ashramName: "",
      address: "SH 29, Devasamudra, Kampli Taluka, Ballary District",
      mobile: ["9833588101"],
      cropDiversity: "Fruits - Mosumbi, Banana, Sapota, Jamun, Sitafal, Lemon, Papaya etc",
    },
    {
      slNo: 81,
      name: "ಗೋಪಾಲಕೃಷ್ಣ",
      ashramName: "",
      address: "752, 3rd stage IPS nagara, Mysore",
      mobile: ["9900457113"],
      cropDiversity: "Spiritual plants, fruit plants",
    },
    {
      slNo: 82,
      name: "ನಿರಂಜನ್ ಪೋಳ್ಯ",
      ashramName: "ಮಾತೃಶ್ರೀ, ಚೋಮಡ್ಕ ಫಾರ್ಮ್ಸ",
      address: "ಶಾಂತಿಗೋಡು ಗ್ರಾಮ ಮತ್ತು ಅಂಚೆ, ಪುತ್ತೂರು - 574202",
      mobile: ["9481917879"],
      cropDiversity: "ಅಡಿಕೆ, ತೆಂಗು, ಬಾಳೆ, ಕಾಳುಮೆಣಸು, ಕಾಫಿ, ಕೊಕೊ ಹಾಗೂ ವಿವಿಧ ಹಣ್ಣಿನ ಮರಗಳು",
    },
    {
      slNo: 83,
      name: "Vittal A Kaadimageri Baragundi",
      ashramName: "",
      address: "ಬರಗುಡಿ, ತಾಲೂಕ ಇಂಡಿ, ಜಿಲಾ ವಿಜಯಪುರ, ಪಿನ್ 586211",
      mobile: ["8197641736"],
      cropDiversity: "ಕಬು, ಗೋದಿ, ಜೋಳ, ಕಡಲೆ, ಉಲ್ಲಾಗಡ್ಡಿ, ಶೆಂಗಾ, ತೊಗರಿ, ಉದ್ದು, ಹೆಸರು",
    },
    {
      slNo: 84,
      name: "Mangala Narayana",
      ashramName: "",
      address: "#8, Putta guudu/Sri Sai nilaya, Lakshman Reddy Layout, Kodathi, carmelaram post, Sarjapur road, Bengaluru 35",
      mobile: ["9886488679"],
      cropDiversity: "Coconut, Banana, cashew",
    },
    {
      slNo: 85,
      name: "ಶಶಿಕುಮಾರ ಎಂ",
      ashramName: "",
      address: "S.no 46/2, ದೊಡ್ಡತುಪ್ಪೂರು ಗ್ರಾಮ, ಗುಂಡ್ಲುಪೇಟೆ ತಾಲೂಕು",
      mobile: ["9611491313"],
      cropDiversity: "ಹಣ್ಣಿನ ಬೆಳೆಗಳು, ನಿಂಬೆ, ರಸಬಾಳೆ, ಏಲಕ್ಕಿ ಬಾಳೆ, ತೆಂಗು, ನುಗ್ಗೆ, ಖುಷ್ಕಿ ಬೆಳೆಗಳು",
    },
    {
      slNo: 86,
      name: "ನಾಗೇಶ್ ಟಿ ಸಿ",
      ashramName: "",
      address: "ದಾದಪುರ, ಚಿಕ್ಕಜೋಗಿಹಳ್ಳಿ ತಾಂಡಾ",
      mobile: ["6361790601"],
      cropDiversity: "NA",
    },
    {
      slNo: 87,
      name: "ರವಿಕುಮಾರ್ ಕೆ ಎಸ್",
      ashramName: "",
      address: "ಓಬಳಾಪುರ ಗ್ರಾಮ, ಜೆ ಬಿ ಹಳ್ಳಿ ಪಂಚಾಯತ್, ರಾಂಪುರ ಪೋಸ್ಟ, ಮೊಳಕಾಲ್ಮುರು ತಾಲೂಕು",
      mobile: ["9379158279"],
      cropDiversity: "ಬಾಳೆ, ಪಪ್ಪಾಯ, ತೆಂಗು, ಆಡಕೆ, ದಾಳಿಂಬೆ, ಯರಳಿ",
    },
    {
      slNo: 88,
      name: "G Eswara Reddy",
      ashramName: "",
      address: "JALIBENCHI VILLAGE, BELLARY TQ, BELLARY DT",
      mobile: ["9880870709"],
      cropDiversity: "2 acre forest Mahagany, 4ac Coconut coco banana, 1acre pond Banana Drumstick and Border Debbie hebbve, 1acre farmpond",
    },
    {
      slNo: 89,
      name: "ಹೊಯ್ಸಳ ಎಸ್ ಅಪ್ಪಾಜಿ",
      ashramName: "",
      address: "ಉಣ್ಣೆನಹಳ್ಳಿ, ಬೀಚೋನಹಳ್ಳಿ - ಅಂಚೆ, ಹೊಳೆನರಸೀಪುರ ತಾಲೂಕ್, ಹಾಸನ ಜಿಲ್ಲೆ -573211",
      mobile: ["9686182777"],
      cropDiversity: "ಬೆಳೆ - ತೆಂಗು, ಬಾಳೆ, ಅಡಿಕೆ, ಮಾವು, ಸಪೋಟ, ಭತ್ತ, ಕಬು, ಸಿನಮು (ಚಕ್ಕೆ), ಜಾಯ್ಯಕ್ಯ, ಮನೆಗೆ ಬೇಕಾದ ಹಣ್ಣಿನ ಗಿಡಗಳು",
    },
    {
      slNo: 90,
      name: "ಪ್ರಕಾಶ್ ಮಂಚಾಲೆ",
      ashramName: "",
      address: "ಮಂಚಾಲೆ - ಗ್ರಾಮ, ಸಾಗರ - ತಾಲೂಕು, ಶಿವಮೊಗ್ಗ ಜಿಲ್ಲೆ",
      mobile: ["9481935132"],
      cropDiversity: "ಹಲವು ವೈವಿಧ್ಯಮಯ ಸಸ್ಯಗಳು ಮತ್ತು ಮರಗಳು ನಮ್ಮ ತೋಟದಲ್ಲಿ ಇವೆ, ಜೊತೆಗೆ ತೆಂಗು, ಮೆಣಸು, ಅಡಿಕೆ",
    },
    {
      slNo: 91,
      name: "Pompayya Malemath",
      ashramName: "",
      address: "D.no.75, 11th ward, Near Old Bus stand, KAMALAPUR (post) Pin-583221, Hospet (tq), Old Bellary(dt) New Vijayanagara District",
      mobile: ["9449136252"],
      cropDiversity: "Agroforest concept: coconut/Papaya/Mango/Sapota/Guava/Custer apple/Lemon/Curry leaf etc with Some vegetable crops. Also developed a tiny forest",
    },
    {
      slNo: 92,
      name: "ಶಿವಣ್ಣ M E",
      ashramName: "",
      address: "Mikkere, Malavalli-Tq, Mandya-Di",
      mobile: ["6361562597"],
      cropDiversity: "ಭತ್ತ, ರಾಗಿ, ತರಕಾರಿ",
    },
    {
      slNo: 93,
      name: "ವಿಜಯಕುಮಾರ ಶೆಟ್ಟರ",
      ashramName: "",
      address: "ಶಾಹ ಬಜಾರ್, ಬಂಕಾಪುರ-581202, ತಾಲೂಕ - ಶಿಗ್ಗಾವಿ, ಜಿಲ್ಲೆ - ಹಾವೇರಿ",
      mobile: ["8073922845"],
      cropDiversity: "ಯಾವುದೇ ರಾಸಾಯನಿಕ ಬಳಸುತ್ತಿಲ್ಲ ಹಾಗೂ ಈಗ ಸಾವಯವ ಕೃಷಿ ಪ್ರಾರಂಭ ಮಾಡಿದ್ದೇನೆ",
    },
    {
      slNo: 94,
      name: "Mahesh Banavasi, Sirasi",
      ashramName: "",
      address: "Near Jayanti High School Banavasi, Sirsi 581318",
      mobile: ["9739788801"],
      cropDiversity: "8 varieties",
    },
    {
      slNo: 95,
      name: "ನಾಗನಗೌಡ ಭರಮಗೌಡರ",
      ashramName: "",
      address: "ಅಂಚೆ ಉಡಕೇರಿ, ಬೈಲಹೊಂಗಲ ತಾಲೂಕು 591104",
      mobile: ["8448537575"],
      cropDiversity: "ಕಬು, ಸೊಯಾ, ಅವರೆ, ಕಡಲೆ, ನವಣೆ, ಬಿದಿರು, ಲಿಂಬೆ, ನೆಲ್ಲಿ, ಸೀತಾಫಲ್, ನೇರಳೆ, ಕೆಂಪುಹುಣಸೆ, ಬೀಟೆ/ಸೀಸಂ, ಬೇವು, ಗಾಳಿಗಿಡ, ಮಹಾಗಣಿ, ಸಂಪಿಗೆ",
    },
    {
      slNo: 96,
      name: "Mallikarjungouda V Patil",
      ashramName: "",
      address: "At post Guddadahulikatti, tq kalaghatagi, Dist Dharwad",
      mobile: ["9972700958"],
      cropDiversity: "Sugarcane, banana, coconut, vegetable",
    },
    {
      slNo: 97,
      name: "ಶ್ರೀಕಾಂತ ಪ ಕುಂಬಾರ",
      ashramName: "",
      address: "ಮುಗಳಕೋಡ 587 113",
      mobile: ["9740813888"],
      cropDiversity: "ಕಬು, ಅರಿಶಿನ, ಕರಿಬೇವು, ನುಗ್ಗೆ, ತೆಂಗು, ಸೀತಾಫಲ ಮತ್ತು ಔಷಧಿಯ ಸಸ್ಯಗಳು",
    },
    {
      slNo: 98,
      name: "Srinivas Joshi",
      ashramName: "",
      address: "Post Bommanahalli 581203, TALUKA HANGAL, DISTRICT HAVERI",
      mobile: ["9821552333"],
      cropDiversity: "NOW PADDY AND SUGARCANE",
    },
    {
      slNo: 99,
      name: "ಶಿವನಂಜಪ್ಪ",
      ashramName: "",
      address: "ನಂಬರ್ 69, ಶ್ರೀ ಶಿವ ಕುಟೀರ, ಬಂಜಾರ ಪಾಳ್ಯ, ತಾತಗುಣಿ ಅಂಚೆ, ಕನಕಪುರ ರಸ್ತೆ, ಬೆಂಗಳೂರು 560 8-2",
      mobile: ["9742593170"],
      cropDiversity: "ತೋಟಗಾರಿಕೆ ಬೆಳೆಗಳು, ತರಕಾರಿಗಳು, ಹಣ್ಣುಗಳು, ಸುಮಾರು ಹತ್ತು ವರ್ಷಗಳಿಂದ ಯಾವುದೇ ರಾಸಾಯನಿಕ ಬಳಸದೆ ಗೋವಾ ಆಧಾರಿತ ಕೃಷಿ",
    },
    {
      slNo: 100,
      name: "ಶಂಕರೇ ಗೌಡ",
      ashramName: "",
      address: "ಮುದೇನೂರು, ರಾಣಿಬೆನ್ನೂರು - ತಾಲೂಕು, ಹಾವೇರಿ ಜಿಲ್ಲೆ",
      mobile: ["9740351173"],
      cropDiversity: "ಅಡಿಕೆ, ತೆಂಗು, ಬಾಳೆ, ನಿಂಬೆ, ನೂರಾರು ಬಗೆಯ ಸಸ್ಯ ವೈವಿಧ್ಯತೆ, ಜೀವ ವೈವಿಧ್ಯತೆಗಳಿಂದ ಕೂಡಿದೆ",
    },
    {
      slNo: 101,
      name: "H S Kiran Kumar",
      ashramName: "",
      address: "No.48, 4th Cross, Khadi layout",
      mobile: ["9108279930"],
      cropDiversity: "Horticulture",
    },
    {
      slNo: 102,
      name: "ಸಿದ್ದರಾಮ ಡಮಾಮಿ",
      ashramName: "",
      address: "ಪೋಸ್ಟ: ಭೂಯ್ಯಾರ",
      mobile: ["8747867675"],
      cropDiversity: "ಕಬು, ತೊಗರಿ, ಕಡಲೆ",
    },
    {
      slNo: 103,
      name: "ಗಂಗಾಧರ ತಳವಾರ",
      ashramName: "",
      address: "At Post: Bhuyar, Taq: Indi, Dist: Bijapur",
      mobile: ["7760951359"],
      cropDiversity: "ತಾಳೆ, ಪೆರು, ತೆಂಗು",
    },
    {
      slNo: 104,
      name: "ಜಯಪ್ರಕಾಶ ಬಿ ಪಾಟೀಲ",
      ashramName: "",
      address: "ಜೆ ಬಿ ಪಾಟೀಲ ಕುಂದೂರು",
      mobile: ["9845985927", "9535533927"],
      cropDiversity: "ಗೋವಿಂಜೆಲ್",
    },
    {
      slNo: 105,
      name: "ರಮೇಶ ಮಲ್ಲಪ್ಪ ಪಾಟೀಲ",
      ashramName: "",
      address: "ಮು/ಪೋಸ್ಟ ಕೊಠಬಾಗಿ, ತಾಲೂಕ ಹುಕ್ಕೇರಿ, ಜಿಲಾ ಬೆಳಗಾವಿ 591306",
      mobile: ["6363414479"],
      cropDiversity: "ಕಬು, ಉದ್ದು, ಹೆಸರು, ಗೋದಿ, ಜವೇಗೋದಿ, ಗೋವಿನ ಜೋಳ, 23 ಪ್ರಬೇಧಗಳ ಒಟ್ಟು 270 ಗಿಡಗಳು",
    },
    {
      slNo: 106,
      name: "Mahadev babu dharmoje",
      ashramName: "",
      address: "Nanadi cross, factory road, gurukrupa farmhouse",
      mobile: ["9880769140"],
      cropDiversity: "Deshi balehannu, kabbu, mavinhannu, tengu etc",
    },
    {
      slNo: 107,
      name: "ನಿಂಗನಗೌಡ ಪರಸನಗೌಡ ಕಾಳಿಂಗೌಡ್ರ",
      ashramName: "",
      address: "ನಿಂಗನಗೌಡ ಪ ಕಾಳಿಂಗೌಡ್ರ",
      mobile: ["9880260052"],
      cropDiversity: "ತೆಂಗು, ಬಾಳೆ, ನುಗ್ಗೆ, ಕಬು, ಗೋವಿನ ಜೋಳ, ಬೇವು, ತೇಗು, ಎಲ್ಲ ತರಹದ ಹಣ್ಣು ಹಾಗೂ ತರಕಾರಿ",
    },
    {
      slNo: 108,
      name: "ಶಂಕರ್ ಈ ಸೊಗಲಿ",
      ashramName: "",
      address: "ಪೂ - ಕುನ್ನೂರ 581193, ತಾ - ಶಿಗ್ಗಾಂವಿ, ಜಿ - ಹಾವೇರಿ",
      mobile: ["9738434329"],
      cropDiversity: "ಅಡಿಕೆ, ಬಾಳೆ, ನಿಂಬೆ, ಕರಿಬೇವು, ಅರಸಿನ, ಔಷಧಿ ಸಸ್ಯಗಳು, ಶ್ರೀಗಂಧ, ಏಲಕ್ಕಿ, ಬಹುವಾರ್ಷಿಕ ಸಸ್ಯಗಳು ಮತ್ತು ಮೌಲ್ಯ ವರ್ಧನೆ",
    },
    {
      slNo: 109,
      name: "ಮಳ್ಳಪ್ಪ ತಿ ಹೊನ್ನಿಹಳ್ಳಿ",
      ashramName: "",
      address: "ಸಾ.ಬೀರವಳ್ಳಿ, ತಾ.ಕಲಘಟಗಿ, ಜಿ.ಧರವಾಡ",
      mobile: ["9591891907"],
      cropDiversity: "ಭತ್ತ, ಸಾವಿರಾಗಿ, ಹುರಳಿ, ಕರೆ, ಹೋಸರು, ಜವಾರಿ, ತೊಗರೆ, ಮಾವು, ಹುಣಸೆ, ನೆಲ್ಲಿ, ಪೆರಲ, ಬೇವು, ಬೀಳಿ, ಮತ್ತೆಗೀಡ, ಸಗವಾನಿ ಮುಂತಾದವುಗಳು",
    },
    {
      slNo: 110,
      name: "Channabasavaraj shankarappa Korishetti",
      ashramName: "",
      address: "C/O, S. I Korishetti, At. Varavi, yakkeri, Tq. Savadatti, Dist. Belgaum-591 117",
      mobile: ["9738946742"],
      cropDiversity: "ಮಾವು, ತೆಂಗು, ನುಗ್ಗೆ, ಕರಿಬೆವು, ಬಾಳೆ, ಪಪ್ಪಾಯ",
    },
    {
      slNo: 111,
      name: "ಕೆ ಎನ್ ದೊಡ್ಡಬಸವನಗೌಡ",
      ashramName: "",
      address: "ಚಳ್ಳಗುಕಿ, ತಾಲೂಕು: ಬಳ್ಳಾರಿ, ಜಿಲಾ: ಬಳ್ಳಾರಿ, ವಿಧಾನಸಭಾ: ಬಳ್ಳಾರಿ ಗ್ರಾಮಾಂತರ ಕ್ಷೇತ್ರ",
      mobile: ["9449171590"],
      cropDiversity: "ತೋಟಗಾರಿಕೆ ಬೆಳೆಗಳು, ಉದಾಹರಣೆ ನುಗ್ಗೆ, ಸೀಬೆ, ನಿಂಬೆ, ಸೀತಾಫಲ, ನೇರಳೆ, ಮಾವು",
    },
    {
      slNo: 112,
      name: "Suprith",
      ashramName: "",
      address: "ಸುಪ್ರೀತ್ ನಾರಾಯಣ ಗೌಡ, ಅದಗೂರು",
      mobile: ["9535695808"],
      cropDiversity: "ಸುಮಾರು 200 ಹೆಚ್ಚು ವೈವಿಧ್ಯತೆಯನ್ನು ತಿಳಿಸಬಹುದು",
    },
    {
      slNo: 113,
      name: "ರಘು ಮಾರುತಿ ಡಿ ಕೆ",
      ashramName: "",
      address: "ಓಂ ಶಾಂತಿ, ಶಿವಾಲಯ ಶುಭಾಶ ನಗರ, ಕೆ ಆರ್ ನಗರ, ಮೈಸೂರು ಜಿಲ್ಲೆ",
      mobile: ["9740025117"],
      cropDiversity: "ಆಯುವೇದ ಗಿಡ, ಒಳಾಂಗಣ ಗಿಡ",
    },
    {
      slNo: 114,
      name: "ವೆಂಕಟೇಶ್ ಏನ್",
      ashramName: "",
      address: "ಕಣಗಾಲು, ಕೆ ಆರ್ ನಗರ ತಾಲೂಕು, ಮೈಸೂರು ಜಿಲಾ",
      mobile: ["7975656833"],
      cropDiversity: "ಅಡಿಕೆ, ತೆಂಗು, ಮಾವು, ಬಾಳೆ, ಮೆಣಸು ಮತ್ತು ಇತರೆ ತೋಟಗಾರಿಕಾ ಬೆಳೆಗಳು",
    },
    {
      slNo: 115,
      name: "ಭಾಸ್ಕರ ಶೆಟ್ಟಿ",
      ashramName: "",
      address: "ಕಣಗಾಲು, ಕೃಷ್ಣಮೂರ್ತಿ ತೋಟ",
      mobile: ["7483825635"],
      cropDiversity: "ಅಡಿಕೆ, ಬಾಳೆ, ಕೊಕೊ, ಕಾಳು ಮೆಣಸು, ಇತ್ಯಾದಿ",
    },
    {
      slNo: 116,
      name: "ಬಿ ವೀರಭದ್ರಪ್ಪ ಮತ್ತು ಬಿ ವಿಹರ್ಷ",
      ashramName: "",
      address: "ಮುನುಗನಹಳ್ಳಿ ಗ್ರಾಮ, ಕೆ ಆರ್ ನಗರ ತಾಲೂಕು",
      mobile: ["9910301810"],
      cropDiversity: "ಮೆಣಸು, ಅಡಿಕೆ, ಕೊಕೊ, ಮಾವು ಮತ್ತು ಇತರೆ ತೋಟಗಾರಿಕಾ ಬೆಳೆಗಳು",
    },
    // Add these after ashram #116 in your ashrams array:
    {
      slNo: 117,
      name: "ಲೋಕೇಶ್ ಕೆ ವಿ",
      ashramName: "",
      address: "ಕಣಗಾಲು, ಕೆ ಆರ್ ನಗರ ತಾಲೂಕು, ಮೈಸೂರು ಜಿಲ್ಲೆ",
      mobile: ["9449245975"],
      cropDiversity: "ತೆಂಗು ಅಡಿಕೆ ಕೆಲವು ಹಣ್ಣುಗಳು",
    },
    {
      slNo: 118,
      name: "ರಾಮದಾಸ ಬುಡ್ಲಹಟ್ಟಿ",
      ashramName: "",
      address: "ಬುಡ್ಲಹಟ್ಟಿ, ಚಳ್ಳಕೆರೆ ತಾಲೂಕು, ಚಿತ್ರದುಗ ಜಿಲ್ಲೆ",
      mobile: ["9449185775"],
      cropDiversity: "ಅಡಿಕೆ ಸಪೋಟ ಏಲಕ್ಕಿ, ಕಾಳುಮೆಣಸು ಇತರೆ",
    },
    {
      slNo: 119,
      name: "ಬಿ ಆರ್ ರಘು ರಾವ್",
      ashramName: "",
      address: "ಮಾರುತಿ ನಗರ ತಾವರೆಕೆರೆ ರಸ್ತೆ, ಬುಕ್ಕಾಪಟ್ಟಣ, ಶಿರಾ ತಾಲೂಕು, ತುಮಕೂರು ಜಿಲ್ಲಾ",
      mobile: ["8722943106"],
      cropDiversity: "ಶ್ರೀಗಂಧ ಹಲಸು, ಹುಣಿಸೆ ತೆಂಗು ಅಡಿಕೆ",
    },
    {
      slNo: 120,
      name: "ನಾಗಪ್ಪ ಗೌಡ ಪಾಟೀಲ್",
      ashramName: "",
      address: "ಸಿಡ್ಡಿಹಳ್ಳಿ, ಕೆರೆಹಳ್ಳಿ - ಅಂಚೆ, ಸೋರಬ ತಾಲೂಕು, ಶಿವಮೊಗ್ಗ ಜಿಲ್ಲೆ",
      mobile: ["9980475624"],
      cropDiversity: "ವಿವಿಧ ರೀತಿಯ ಔಷಧೀಯ ಸಸ್ಯಗಳು",
    },
    {
      slNo: 121,
      name: "ರಂಗಸ್ವಾಮಿ ಕೆ",
      ashramName: "",
      address: "ಹುಲಿಕುಂಟೆ ಚಳ್ಳಕೆರೆ ತಾಲೂಕು ಚಿತ್ರದುಗ ಜಿಲ್ಲೆ",
      mobile: ["9900489333"],
      cropDiversity: "ಅಡಿಕೆ ತೆಂಗು ಮಾವು ಅರಸು ನಿಂಬೆ ಸೀತಾಫಲ ಇತ್ಯಾದಿ",
    },
    {
      slNo: 122,
      name: "ಅರುಣ್ ಎಂ",
      ashramName: "",
      address: "ಹೆಬಾಳು ಕೆ ಆರ್ ನಗರ ತಾಲೂಕು ಮೈಸೂರು ಜಿಲ್ಲಾ",
      mobile: ["9341920509"],
      cropDiversity: "ಹಣ್ಣಿನ ಗಿಡಗಳು ತೆಂಗು ಬಾಳೆ ಪರಂಗಿ ಅಡಿಕೆ ಹಲಸು ಮಾವು",
    },
    {
      slNo: 123,
      name: "ಬಿ ಎನ್ ಸಿದ್ದಲಿಂಗೇಶ್ವರ",
      ashramName: "",
      address: "ದೊಡ್ಡಬೊಮ್ಮನಹಳ್ಳಿ ಅರಕಲಗೂಡು ತಾಲೂಕು ಹಾಸನ ಜಿಲ್ಲೆ",
      mobile: ["8971020469"],
      cropDiversity: "ರಾಜಮುಡಿ ಭತ್ತ ಅರಿಶಿಣ ಶುಂಠಿ ಬೆಳೆ ಕಾಳುಗಳು ತೆಂಗು ವಿವಿಧ ಬಗೆಯ ಬಾಳೆಯ ಸುಮಾರು 30 ರೀತಿಯ ಹಣ್ಣುಗಳು",
    },
    {
      slNo: 124,
      name: "ಜಾನೇಶ್ವರ ಕೆ ಆರ್",
      ashramName: "",
      address: "",
      mobile: ["9916061765"],
      cropDiversity: "50 ಜಾತಿಯ ಹಣ್ಣು ತರಕಾರಿ ದಾನ್ಯ",
    },
    {
      slNo: 125,
      name: "Guru g Katapurimath",
      ashramName: "",
      address: "At/Post Sampgaon 591125",
      mobile: ["8970348189"],
      cropDiversity: "Kabbu, soyabean, vegetables, jawar, bengal gram",
    },
    {
      slNo: 126,
      name: "ತಿಪ್ಪಣ್ಣ S",
      ashramName: "",
      address: "ಎಸ್ ತಿಪ್ಪಣ್ಣ ಸನ್ ಆಫ್ ಸಿದ್ದಣ್ಣ ಪೂಜಾರಟ್ಟಿ ಹಾನಗಲ್",
      mobile: ["9972921880", "7022248856"],
      cropDiversity: "ನೈಸಗಿಕ ಕೃಷಿಯಾಗಿ ಸೀತಾಫಲ, ಶ್ರೀಗಂಧ, ರಕ್ತ ಚಂದನ ಇತ್ಯಾದಿಗಳು",
    },
    {
      slNo: 127,
      name: "ಮಹಾವೀರ್",
      ashramName: "ಮಹಾವೀರ ಸುಭಾಸ್",
      address: "ಕಾಮನಕೋರಿ",
      mobile: ["9611182129"],
      cropDiversity: "ಲಿಂಬೆ",
    },
    {
      slNo: 128,
      name: "ಕರಿಸಿದ್ಧನಗೌಡ ಮಾಲಿ ಪಾಟೀಲ",
      ashramName: "",
      address: "ವಿಜಯಕಲ್ಯಾಣ, ಶ್ರೀ ಬಸವೇಶ್ವರ ದೇವಾಲಯ ಹತ್ತಿರ, 1ನೇ ವಾರ್ಡ, ಗೌಡರ ಓಣಿ, ಬೂದಗುಂಪ ತಾಲೂಕು ಕಾರಟಗಿ ಜಿಲ್ಲಾ ಕೊಪ್ಪಳ 583229",
      mobile: ["9945195785"],
      cropDiversity: "ಮಾವು, ತೆಂಗು, ಬಾಳೆ, ನಿಂಬೆ, ಅಡಿಕೆ",
    },
    {
      slNo: 129,
      name: "Rajeev R",
      ashramName: "",
      address: "No 26, pura grama, hamapura hobli, HD KOTE taluk",
      mobile: ["9019906699"],
      cropDiversity: "4-5",
    },
    {
      slNo: 130,
      name: "ಸುಜಾತ. P. R.",
      ashramName: "",
      address: "#222, E ಬ್ಲಾಕ್, ಮೂರನೇ ಹಂತ, ವಿಜಯನಗರ, ಮೈಸೂರು 570030",
      mobile: ["9449668536"],
      cropDiversity: "ತೆಂಗು, ಅಡಿಕೆ, ಬಾಳೆ, ಕಾಫಿ, ಮೆಣಸು, ಮಾವು, ಸೀಬೆ, ನೆಲ್ಲಿ, ಸಪೋಟ, ನೇರಳೆ, ಬಟರ್ ಫ್ರೀ ನಟ್, ಪಪ್ಪಾಯ ಮತ್ತು 20 ವಿವಿಧ ಹಣ್ಣು ಮತ್ತು ತರಕಾರಿಗಳು",
    },
    {
      slNo: 131,
      name: "ಡಾ. ಪವತಗೌಡ ಬ ಹಿರೇಗೌಡರ",
      ashramName: "",
      address: "ವಿವೇಕ ವೈಭವ, ಶ್ರೀ ಸ್ವಾಮಿ ವಿವೇಕಾನಂದ ನಗರ, ಕೊಪ್ಪಳ ರೋಡ್ ಮುಂಡರಗಿ 582118",
      mobile: ["9481486606"],
      cropDiversity: "ತೆಂಗು, ಮಾವು, ಹಲಸು, ಚಿಕ್ಕು, ಜಂಬೂ, ನೆಲ್ಲಿ, ಗೆಣಸು, ದಾಳಿಂಬೆ, ಬಾಳೆ, ಸೀತಾಫಲ, ನೋನಿ, ದಾಸವಾಳ, ಪಂಚವಟಿ ಸಸ್ಯಗಳು, ಒಟ್ಟು 118 ಆಹಾರ ಮತ್ತು ಔಷಧ ಸಸ್ಯಗಳ ಸಂಗ್ರಹ",
    },
    {
      slNo: 132,
      name: "ಸದಾನಂದ ಮುದುಕಪ್ಪ ಕುರಿ",
      ashramName: "",
      address: "",
      mobile: ["9110258104"],
      cropDiversity: "ಸಾವಯವ ತರಕಾರಿಗಳು",
    },
    {
      slNo: 133,
      name: "Shivananjappa",
      ashramName: "",
      address: "No 69, Sri Shiva Kuteera, Banjarapalya, Tatguni post, Off Kanakapura road, Bengaluru 560082",
      mobile: ["9742593170"],
      cropDiversity: "Coconut, Mango Chiku, Butterfruit, Aloveera, Curry leaves, etc",
    },
    {
      slNo: 134,
      name: "D J Basavaraju",
      ashramName: "",
      address: "S/O B Javaregowda, Devihalli, Goni Tumakuru post, Debaghata hobli, Turuvekere, Tumakuru 572227",
      mobile: ["9141682049"],
      cropDiversity: "Coconut, Areka, Banna, Wild Pepper, Sebi gidi, Sithapala, Apple, Betadnele, Nerale, Butterfruit, etc",
    },
    {
      slNo: 135,
      name: "Sudhamani G V",
      ashramName: "",
      address: "Goni Tumakuru post, Debhaghata Hobli, Turuvekere Taluk, Tumakuru 572227",
      mobile: ["8971196937"],
      cropDiversity: "Coconut, Areka, Apple, Pineapple, Sapota, Waterapple, Nerale, Sebekai, etc",
    },
    {
      slNo: 136,
      name: "Pushpalatha P",
      ashramName: "",
      address: "Mahadeshwaranagar, 1st cross, Sathnur Road, Chenpatna Taluk, Ramanagara 562160",
      mobile: ["8197952619"],
      cropDiversity: "Coconut, Raggi, Kakada flowers",
    },
    {
      slNo: 137,
      name: "ಎಸ್ ಕಾರ್ತಿಕ್",
      ashramName: "",
      address: "#9, 13ನೇ ಕ್ರಾಸ್, 3ನೇ ಮುಖ್ಯ ರಸ್ತೆ ಜವರೇಗೌಡ ನಗರ ರಾಜರಾಜೇಶ್ವರಿ ನಗರ ಬೆಂಗಳೂರು 560098",
      mobile: ["9986507527"],
      cropDiversity: "ರಾಸುಗಳ ಮೇವಿನ ಬೆಳೆ ಹಾಗೂ ಮಾವಿನ ಮರಗಳು",
    },
    {
      slNo: 138,
      name: "Virupakshi reddy",
      ashramName: "",
      address: "Yelasatti, konkal Hobli, Gurumitkal Tq, Yadagir Dist. 585315",
      mobile: ["9844689056"],
      cropDiversity: "ಭತ್ತ, ನೆಲಗಡಲೆ, ಸೂರ್ಯಕಾಂತಿ",
    },
    {
      slNo: 139,
      name: "ಜಿ.ಎಸ್.ಕಮತರ",
      ashramName: "",
      address: "ವಚನಸದನ, ಬಸವನಗರ, ಮಾನವಿ, ಜಿ.ರಾಯಚೂರು",
      mobile: ["9945095606"],
      cropDiversity: "ಪ್ರಸಕ್ತ ವರ್ಷದಿಂದ ಲಿಂಬೆ ಪ್ರಧಾನ ಪಂಚತರಂಗಿಣಿ ಬನ ನಿರ್ಮಾಣ. ಮೀನು-ಕೋಳಿ ಸಾಕಾಣಿಕೆಗೆ ಕೆರೆ ನಿರ್ಮಾಣ, ಸುರಕ್ಷತೆಗಾಗಿ ಸೋಲಾರ್ ಬೇಲಿ, ಸೋಲಾರ್ ಸಿಸಿ ಕೆಮೆರಾ ಅಳವಡಿಕೆ",
    },
    {
      slNo: 140,
      name: "MD Ismail Khalndar khan Mulla",
      ashramName: "",
      address: "Kamlanagar at/post tadas tq. Shiggon dist. Haveri karnataka",
      mobile: ["9986938667"],
      cropDiversity: "100",
    },
    {
      slNo: 141,
      name: "Shivkumar",
      ashramName: "Kamadhenu goushale",
      address: "nagora",
      mobile: ["7411993300"],
      cropDiversity: "Innu start madilla",
    },
    {
      slNo: 142,
      name: "Krishna Murthy H l",
      ashramName: "",
      address: "S/o lingappa r s road near sbi ammasandar dandinashivra post thuruvekere tq Tumkur dist pin 572215",
      mobile: ["8951842876"],
      cropDiversity: "Coconut bannana red sandal wood areca nut",
    },
    {
      slNo: 143,
      name: "Udaya Kumar Santhosh",
      ashramName: "",
      address: "S/o. Late Padmanabha shettt, bD. No. 20-251, Bondala Antharagutthu, Shamboor Post, Panemangalore, Bantwal Taluk",
      mobile: ["9448330916"],
      cropDiversity: "ಅಡಿಕೆ, ತೆಂಗು, ಬಾಳೆ, ಕಾಳುಮೆಣಸು, ಗದ್ದೆ, ತರಕಾರಿ",
    },
    {
      slNo: 144,
      name: "Siddesh G C",
      ashramName: "Niha krishi ashrama",
      address: "Danavadi Road",
      mobile: ["9611193344"],
      cropDiversity: "Coconut, nutmeg, coco, all leaf",
    },
    {
      slNo: 145,
      name: "ಶಿವರಾಜ ಬಿ ಪಾರಗೊಂಡ",
      ashramName: "",
      address: "At Post - Salotagi Taluka - Indi District - Vijayapur Karnataka -586217",
      mobile: ["7722006731"],
      cropDiversity: "ಕಾಡು ಕೃಷಿ ಕರ್ಶಾಲೆ, Five Layer Lemon Model & All Pulses",
    },
    {
      slNo: 146,
      name: "ಅಶೋಕ ce",
      ashramName: "",
      address: "ಚಂಬೇನಹಳ್ಳಿ, ಸಜ್ಜೆ ಹೊಸಹಳ್ಳಿ ಪೋಸ್ಟ, ದೊಡ್ಡೇರಿ ಹೋಬಳಿ, ಮಧುಗಿರಿ ತಾಲೂಕು, ತುಮಕೂರು ಜಿಲ್ಲೆ",
      mobile: ["9110422133"],
      cropDiversity: "ಹಣ್ಣಿನ ಗಿಡಗಳು",
    },
    {
      slNo: 147,
      name: "Madhusudana HN",
      ashramName: "Honnasiri krushi ashrama",
      address: "Honnapura, kotagaralahalli post, madhugiri taluk, thumkur district",
      mobile: ["9902776676"],
      cropDiversity: "ಅಡಿಕೆ, ತೆಂಗು, ಬಾಳೆ, ಸೀಬೆ, ಮೆಣಸು, ಕಾಫಿ, ಏಲಕ್ಕಿ, ತರಕಾರಿಗಳು, ಸೊಪ್ಪು, ಹಣ್ಣುಗಳು",
    },
    {
      slNo: 148,
      name: "Susheela Kumar",
      ashramName: "",
      address: "Sy No. 7/1, 121/1 and 120/2, Alavady village, Bomanahalli Panchayat, Terakanambi hobli, Gundlulpet Taluk, Chamrajnagar Dist",
      mobile: ["9945404150", "9353339220"],
      cropDiversity: "Forestry, Fruit, Medicine, Rare and Horticulture plants",
    },
    {
      slNo: 149,
      name: "Santoshkumar",
      ashramName: "",
      address: "Kamalakanda plot.no. 22 sy no. 36/aa, annapurneswari colony kusnoor road",
      mobile: ["9480008529"],
      cropDiversity: "200+ plants",
    },
    {
      slNo: 150,
      name: "ಸಂದೀಪ್ ಮಂಜುನಾಥ್",
      ashramName: "S 4 Naturals farm",
      address: "Opposite Hunsur Plywood Factory BM Road Hunsur 571105",
      mobile: ["9480797169"],
      cropDiversity: "ನೂರಾರು ಸಸ್ಯ ಪ್ರಭೇದಗಳಿವೆ",
    },
    {
      slNo: 151,
      name: "N. G. MUKESH",
      ashramName: "GVRE FOUNDATION",
      address: "G.G. CAMP, HOSUDI P.O. SHIVAMOGGA TQ. DT.",
      mobile: ["9243089306"],
      cropDiversity: "We Have MORE THAN 20 VARITIES ON A SIX ACRE PLOT OF WHICH 12 GUNTAS IS EXCLUSIVELY KEPT FOR KRISHI ASHRAM",
    },
    {
      slNo: 152,
      name: "Purneshappa N B",
      ashramName: "",
      address: "ಮೇಲೆನಂತೆ",
      mobile: ["9686808060"],
      cropDiversity: "ಅಡಿಕೆ",
    },
    {
      slNo: 153,
      name: "ಸುರೇಶ ಕೆ.ಟಿ.",
      ashramName: "",
      address: "ಕೊಂಗಳ್ಳಿ ಗ್ರಾಮ, ವನಗೂಡು ಹ್ಯಾಂಡ್ ಪೋಸ್ಟ 573123, ಯಸಳೂರು ಹೋಬಳಿ, ಷಸಕಲೇಶಪುರ ತಾಲೂಕು, ಹಾಸನ ಜಿಲ್ಲೆ",
      mobile: ["9342349255"],
      cropDiversity: "ಏಲಕ್ಕಿ ಕಾಫಿ ಭತ್ತ ಮೆಣಸು",
    },
    {
      slNo: 154,
      name: "Bapugouda K Patil",
      ashramName: "",
      address: "Bapugouda patil At post Kundur Bankapur road #335 Tq Shiggoan",
      mobile: ["9448029458"],
      cropDiversity: "Mango, Guava, cashew nuts, etc Soyabean, black gram, maze etc",
    },
    {
      slNo: 155,
      name: "Mallayya",
      ashramName: "",
      address: "Jagir pannur, po- chikalparvi tq-manvi dist-raichur",
      mobile: ["7899718663"],
      cropDiversity: "Surykanti, atti, thogari, jola, sajje, hesru",
    },
    {
      slNo: 156,
      name: "ಶ್ರೀಧರ ಹುಲ್ಲುಮನೆ",
      ashramName: "",
      address: "೫೩೮, ೩ನೇ ಮಹಡಿ, ೮-ಎ ಮುಖ್ಯ ರಸ್ತೆ, ಯಲಹಂಕ ಉಪನಗರ ಬೆಂಗಳೂರು",
      mobile: ["9449638238"],
      cropDiversity: "ಹಣ್ಣು, ತರಕಾರಿ ಮತ್ತು ಔಷಧ ಸಸ್ಯಗಳು",
    },
    {
      slNo: 157,
      name: "Pawankumar Angadi",
      ashramName: "",
      address: "Atpost-Hulkund Tq-Ramdurg Dist-Belagavi state-Karnataka -591114",
      mobile: ["7411085171"],
      cropDiversity: "20",
    },
    {
      slNo: 158,
      name: "Sharadkumar Patil",
      ashramName: "Dr B B Patil organic farm",
      address: "Salotagi, Indi taluk, Vijayapur District",
      mobile: ["447912649659"],
      cropDiversity: "ಕಬು, ತೊಗರಿ, ಜೋಳ, ಗೋದಿ, ಅಗಸಿ",
    },
    {
      slNo: 159,
      name: "Dr. Chandrakanth M. Kalbavi",
      ashramName: "",
      address: "Campus Head.Agril EXTN. Education Centre. Huvinahadagli",
      mobile: ["9845675485"],
      cropDiversity: "Agril. floriculture, vegetables",
    },
    {
      slNo: 160,
      name: "ಈರನಗೌಡ ಬ, ಪಾಟೀಲ",
      ashramName: "",
      address: "ಆಕಾಶಗಂಗಾ ನಿಲಯ, ಶಿವಾಜಿ ವೃತ್ತ ಹತ್ತಿರ. ಕಟಕೋಲ. ರಾಮದುಗ, ಬೆಳಗಾವಿ",
      mobile: ["9972942938"],
      cropDiversity: "ಕಬು, ಅರಿಸಿನ, ತರಕಾರಿ, ಕಿರುದಾನ್ಯ. ಯಣ್ಣೆಕಾಳು, ತೆಂಗು, ಮಾವು. ಪೇರಳೆ, ಬಾಳೆ, ಸೀತಾಪಲ್, ಕರಬೇವು, ಸಾಗವಾಣಿ",
    },
    {
      slNo: 161,
      name: "ಶಾಂತಾರಾಮ ಕಾಮತ",
      ashramName: "",
      address: "119, ಮುಖ್ಯ ರಸ್ತೆ, ಕುಂಭಾರವಾಡಾ, ಜೋಯಿಡಾ ತಾಲೂಕ",
      mobile: ["9448895133"],
      cropDiversity: "ಭತ್ತ ಮಳೆ ಯಾಶ್ರಿತ, ತೆಂಗು, ದಾಲಚಿನಿ, ಅಡಿಕೆ, ಗೆಡ್ಡೆ ಗೆಣಸುಗಳು",
    },
    {
      slNo: 162,
      name: "ಗೀತಾ ಟಿ ಹಿಮ",
      ashramName: "",
      address: "ಸಿರಿ, ಆಲೂರು",
      mobile: ["9845400823"],
      cropDiversity: "ತೆಂಗು ಬಾಳೆ ಅಡಿಕೆ",
    },
    {
      slNo: 163,
      name: "Shivanand Shivapujimath",
      ashramName: "",
      address: "Silver Bell Apartment, Vidhyagiri Dharwad",
      mobile: ["9480766789"],
      cropDiversity: "All types of fruits & forest plants",
    },
    {
      slNo: 164,
      name: "Rakesh CN",
      ashramName: "",
      address: "Basaveshwara badavane old pb road Davanagere",
      mobile: ["9916429793"],
      cropDiversity: "Adike Nugge",
    },
    {
      slNo: 165,
      name: "Manukumar c",
      ashramName: "",
      address: "Hosadoddi g, horalagallu post, kasaba hobli, kanakapura taluk",
      mobile: ["9611243169"],
      cropDiversity: "Warmicompost",
    },
    {
      slNo: 166,
      name: "Chandrashekhar",
      ashramName: "",
      address: "Holinagar sedam near gprs school sedam 585222",
      mobile: ["9440092220"],
      cropDiversity: "Tut, chana dal, Jawar",
    },
    {
      slNo: 167,
      name: "ನವೀನ್ ಕುಮಾರ್ ಎಸ್",
      ashramName: "",
      address: "ಸಂಗಮೇಶ್ವರ ಬಡಾವಣೆ, ಅಕಾಶ್ ವಾಣಿ ಹಿಂಭಾಗ, ಕೊಳಗೊಟ್ಟೆ",
      mobile: ["9342338241"],
      cropDiversity: "",
    },
    {
      slNo: 168,
      name: "A. ಶಿವರಾಮ್",
      ashramName: "",
      address: "ಮಾವಿನಮಡು ಗ್ರಾಮ ಪಿಲಾಲಿ ಅಂಚೆ ಜವನಗೊಂಡನಹಳ್ಳಿ ಹೋಬಳಿ",
      mobile: ["7483823632"],
      cropDiversity: "ಮಾವು, ತೆಂಗು, ಅಡಿಕೆ ಬೇವು ಅರಳಿ ಆಲ ಅತ್ತಿ ದಾಳಿಂಬೆ ಸಪೋಟ ಸೀತಾಫಲ ಪಪ್ಪಾಯಿ ಅಮಟೆಕಾಯಿ ಸುಬಾಬುಲ್ ಹೆಬೇವು ನುಗ್ಗೆ ಶ್ರೀಗಂಧ ನೇರಳೆ ಸೀಬೆ ಬೇಲ ಹುಣಿಸೆ ಗಸಗಸೆ ಹೊಂಗೆ ಹಾಗೂ ಔಷಧೀಯ ಸಸ್ಯಗಳು",
    },
    {
      slNo: 169,
      name: "ಮಳ್ಳಪ್ಪ ಹೊನ್ನಿಹಳ್ಳಿ",
      ashramName: "",
      address: "ಮಳ್ಳಪ್ಪ ತಿ ಹೊನ್ನಿಹಳ್ಳಿ ಸಾ. ಬೀರವಳ್ಳಿ ತಾ.ಕಲಘಟಗಿ ಜಿ.ಧಾರವಾಡ",
      mobile: ["9591891907"],
      cropDiversity: "ಕಬು ಮಾವು ಬತ್ತ ರಾಗಿ ಹೋಸರು ಹುಳ್ಳಿ ಮುಂತಾದವುಗಳು",
    },
    {
      slNo: 170,
      name: "Channabasappa Jayappa",
      ashramName: "Sharada Goushala",
      address: "",
      mobile: ["9483617333"],
      cropDiversity: "Y",
    },
    {
      slNo: 171,
      name: "Anand Shetty",
      ashramName: "",
      address: "Kamprabail house, balthila post & Village, bantwala Taluk",
      mobile: ["7349419085", "9448868972"],
      cropDiversity: "Arrecunut, banana, coco, coconut",
    },
    {
      slNo: 172,
      name: "ಕೇಶವಮೂರ್ತಿ",
      ashramName: "",
      address: "ಕೇಶವಮೂರ್ತಿ ವಿವೇಕಾನಂದ ರಸ್ತೆ ಹುಳಿಯಾರ್ 572218",
      mobile: ["9141639309"],
      cropDiversity: "ತೆಂಗು",
    },
    {
      slNo: 173,
      name: "ವೀರಣ್ಣ ಸಜ್ಜನ",
      ashramName: "ಬಸವ ಗ್ರಾಮೀಣ ಉದ್ಯೋಗ ಗೋ ಕೃಷಿ ಆಶ್ರಮ",
      address: "ವಿಜಯಪುರ ರಸ್ತೆ, ಇಂಗಳೇಶ್ವರ ತಾ.ಬಸವನಬಾಗೇವಾಡಿ, ಜಿ.ವಿಜಯಪುರ",
      mobile: ["9845928550"],
      cropDiversity: "ಜೋಳ, ತೊಗರಿ, ಹೆಸರು, ಅಜವಾನ ಗೋಧಿ, ಕಡಲೆ",
    },
    {
      slNo: 174,
      name: "Lambodar bhat",
      ashramName: "",
      address: "No 80, Bellezea, Narayan gatta village, Bangalore -560099",
      mobile: ["9342016582"],
      cropDiversity: "Fruit trees",
    },
    {
      slNo: 175,
      name: "A.S.Chandrashekharaiah",
      ashramName: "Bhramara Natural Farm",
      address: "Jakkalli village limits, Kollegala Taluk, Chamarajanagar district",
      mobile: ["9845214472"],
      cropDiversity: "Coconut, Areca, Nutmeg, Banana, Coca, Papaya, Moringa, Black pepper. For preparation of Dashaparni Kashaya Agase, honge, Bevu, Lucky leaves and more varieties",
    },
    {
      slNo: 176,
      name: "Hoisala S Appaji",
      ashramName: "",
      address: "S/O Lt. C. Siddappaji, Unnenahalli Va. Beechenahalli po. Halekote hobli, Holenarsipur Tq. Hassan Dist. 573211",
      mobile: ["9686152777"],
      cropDiversity: "Harticultur, Agriculture, Forest",
    },
    {
      slNo: 177,
      name: "ಸಂತೋಷ ಕುಮಾರ್ M.S",
      ashramName: "",
      address: "S/o ಶರಣಪ್ಪ ಮರಿಕುಂಟೆ (p)PIN-577513",
      mobile: ["9900266696"],
      cropDiversity: "ಮೆಕ್ಕೆ ಜೋಳ ರಾಗಿ",
    },
    {
      slNo: 178,
      name: "ಸಚಿನ್ ಬಿ ಕೆ",
      ashramName: "",
      address: "ಸಚಿನ್ ಬಸಪ್ಪ ಕೊಟ್ರಣ್ಣನವರ. ಗೇರಗುಡ್ಡ ಬಸಾಪುರ. ಪೋಸ್ಟ: ಹಿರೇಹುಳ್ಲಾಲ. ಹಾನಗಲ್ ಹಾವೇರಿ",
      mobile: ["7349641138"],
      cropDiversity: "ಸಾವಯವ ತರಕಾರಿ ಮತ್ತು ಬತ್ತ",
    },
    {
      slNo: 179,
      name: "Chdrahari das@ chandavare goeda",
      ashramName: "ಹರೇ ಕೃಷ್ಣ ಜೀವ ಚೈತನ್ಯ ಕೃಷಿ ಆಶ್ರಮ",
      address: "ಮೇಳಾಪುರ ರಸ್ತೆ ಮಹಾದೇವಪುರ ಮಹಾದೇವಪುರ ಪೋಸ್ಟ ಕಸಬಾ ಹೋಬಳಿ ಶ್ರೀರಂಗಪಟ್ಟಣ ತಾಲೂಕು ಮಂಡ್ಯ ಜಿಲ್ಲೆ",
      mobile: ["8105116419"],
      cropDiversity: "ತರಕಾರಿ ನುಗ್ಗೆ ಕರಬೇವು ತೆಂಗು ಮಾವು ಜಾಕಾಯಿ ಮೂಸಿಂಬೆ ಕಿತ್ತಳೆ ಲವಂಗ ನಿಂಬೆ ಸೀಬೆ ಬೇವ ಮಾದಳ ಫಲ ಕಿರಳಿಕಾಯಿ ರಾಮ ಫಲ ಹನುಮಾನ್ ಫಲ ಸೀತಾಫಲ ಬೆಣ್ಣೆ ಹಣ್ಣು",
    },
    {
      slNo: 180,
      name: "ಅಕ್ಷಯ ಆಳ್ವ",
      ashramName: "",
      address: "ಮೇಲಿನಂತೆ",
      mobile: ["8792583425"],
      cropDiversity: "ತೆಂಗು, ಅಡಿಕೆ, ಬಾಳೆ",
    },
    {
      slNo: 181,
      name: "ರವೀಂದ್ರನಾಥ್ ನಾಯ್ಕರ್",
      ashramName: "",
      address: "ಚಿಕ್ಕಹಂದಿಗೋಳ್",
      mobile: ["9480131475"],
      cropDiversity: "ಮಳೆ ಯಾಶ್ರಿತ ಏಕದಳ ಮತ್ತು ದ್ವಿದಳ ಧಾನ್ಯಗಳು",
    },
    {
      slNo: 182,
      name: "C chikkasiddanayaka",
      ashramName: "",
      address: "s/o chikkimadanayaka karepura grama, nanjanagudu thaluk, Mysore district",
      mobile: ["9902647538"],
      cropDiversity: "Jola, baale, thengu",
    },
    {
      slNo: 183,
      name: "Nagaraja gudlanooru",
      ashramName: "",
      address: "s/o basappa uttangi (p) huvin hadagali (t) vijayangara (d)pincode 583219. 1st ward primary school near",
      mobile: ["7893054100"],
      cropDiversity: "Mekkejolla ullagaddi",
    },
    {
      slNo: 184,
      name: "ಡಾ.ಹಾಲತಿ ಸೋಮಶೇಖರ",
      ashramName: "",
      address: "#10, ಪೃಥ್ವಿ ಬಡಾವಣೆ, ದಟ್ಟಗಳ್ಳಿ, ಮೈಸೂರು-570033",
      mobile: ["9886622833"],
      cropDiversity: "ತೆಂಗು. ಅಡಿಕೆ. ಬಾಳೆ, ನುಗ್ಗೆ, ಕೊಕೋ ಇತ್ಯಾದಿಗಳೆಲ್ಲಾ",
    },
    {
      slNo: 185,
      name: "Swadeshi prabhu",
      ashramName: "",
      address: "Ganesh nagar near ganesh mandir LC road Bhalki",
      mobile: ["7829575131"],
      cropDiversity: "-",
    },
    {
      slNo: 186,
      name: "ಡಾ| ಬಸವರಾಜ ಚನ್ನಾವಿ",
      ashramName: "ನೇತ್ರಾವತಿ ಕೃಷಿ ಆಶ್ರಮ",
      address: "ಸಾಸುಗನಹಳ್ಳಿ, ತಾ-ಶಿರಹಟ್ಟಿ, ಜಿ-ಗದಗ",
      mobile: ["7259968715"],
      cropDiversity: "ಮಾವು.ತೆಂಗು. ರೇಷ್ಮೆ. ಬಾಳೆ. ಗೋಡಂಬಿ. ಶ್ರೀಗಂಧ. ಸಾಗವಾನಿ, ಬೇವು. ನೇರಳೆ.ಪಪ್ಪಾಯಿ. ಪೇರಲ. ದಾಳಿಂಬರೆ.ಹಲಸು.ಬಾರಿಹಣ್ಣು. ಕವಳೆ ಹಣ್ಣು. ಹತ್ತಿ ಹಣ್ಣು, ಕರಿಬೇವು. ಸಿರಿಧಾನ್ಯ ಬೆಳೆಗಳು.ದ್ವಿದಳ ಧಾನ್ಯದ ಬೆಳಗಳು. ತರಕಾರಿ ಬೆಳೆಗಳು. ಔಷಧಿ ಸಸ್ಯಗಳು ನುಗ್ಗಿ ಮರಗಳು",
    },
    {
      slNo: 187,
      name: "ಬಸಯ್ಯ ಸ್ವಾಮಿ ಹಿರೇಮಠ",
      ashramName: "",
      address: "ಕಡ್ಡಿರಾಂಪುರ ಹೋಸಪೇಟೆ ತಾಲೂಕು, ವಿಜಯನಗರ ಜಿಲ್ಲೆ",
      mobile: ["9449133154"],
      cropDiversity: "ರಾಮ ಫಲ, ಹನುಮಾನ ಫಲ, ಲಕ್ಷ್ಮಣ ಫಲ, ಸೀತಾಫಲ, ಬ್ರಾಹ್ಮಿ, ಬಾಳೆ ಇತ್ಯಾದಿ ಹಿಪ್ಪಲಿ ಇತ್ಯಾದಿ ಬಾಳೆ ಹಣ್ಣು",
    },
    {
      slNo: 188,
      name: "ಜಿ. ಎನ್ ರುದ್ರಗೌಡ ಪಾಟೀಲ್",
      ashramName: "",
      address: "s/o Nandigoudru Kammathahali post Harapanahalli Taluk Vijaynagar district -583125",
      mobile: ["7406903281"],
      cropDiversity: "ಅಡಿಕೆ ಮತ್ತು ತೆಂಗು",
    },
    {
      slNo: 189,
      name: "ಲಕ್ಷ್ಮೀಗೌಡರು",
      ashramName: "",
      address: "ಕುಂಟನಹಳ್ಳಿ, ದೊಡ್ಡಬಳ್ಳಾಪುರ ತಾಲೂಕು, ಬೆಂಗಳೂರು ಗ್ರಾಮಾಂತರ ಜಿಲ್ಲಾ",
      mobile: ["9844543335"],
      cropDiversity: "ರಾಗಿ, ಜೋಳ, ತೆಂಗು, ಸಿರಿಧಾನ್ಯಗಳು, ಮಾವು, ಹೊಲಸು, ನೇರಳೆ",
    },
    {
      slNo: 190,
      name: "ಅಣ್ಣಪ್ಪ ಭೀಮಪ್ಪ ನವಲಗಟ್ಟಿ",
      ashramName: "",
      address: "ದೇವಲತ್ತಿ ಅಕ್ಕ ತಂಗಿಯರ ಹಾಳ ಅಂಚೆ ಗೋಕಾಕ ತಾಲೂಕು ಬೆಳಗಾವಿ ಜಿಲ್ಲಾ",
      mobile: ["9449925894"],
      cropDiversity: "ಕಬು, ಜೋಳ, ಶೇಂಗಾ, ಸೂರ್ಯಕಾಂತಿ, ಹತ್ತಿ ಕಡಲೆ, ರಾಗಿ, ಎಳ್ಳು",
    },
    {
      slNo: 191,
      name: "ಶ್ರೀಪಾದರಾಜ ಜಿ ಮುರಳಿ",
      ashramName: "",
      address: "ಹೋಸಪೇಟೆ ಕುಷ್ಟಗಿ ರೋಡ್, ಚಿಕ್ಕಬೊಮ್ಮನಾಳ - ಅಂಚೆ, ಕೊಪ್ಪಳ ಜಿಲ್ಲಾ ಮತ್ತು ತಾಲೂಕು",
      mobile: ["9945514000"],
      cropDiversity: "ಭತ್ತ, ತೊಗರಿ, ಹುರಳಿ, ಶೇಂಗಾ, ಸಜ್ಜೆ, ಮೆಕ್ಕೆ ಜೋಳ, ಮೇವಿನ ವಿವಿಧ ತಳಿಗಳು, ಮಾವು, ತೆಂಗು, ನುಗ್ಗೆ, ಗೋಡಂಬಿ, ಸೀತಾಫಲ, ಹುಣಸೇ, ನಿಂಬೆ ಮತ್ತು ವಿವಿಧ ಹಣ್ಣಿನ ಮರಗಳು",
    },
    {
      slNo: 192,
      name: "Marigouda s rayanagoudra",
      ashramName: "",
      address: "at haralakatti t savadatti d belagavi",
      mobile: ["9916204959"],
      cropDiversity: "8 tife",
    },
    {
      slNo: 193,
      name: "B. Annapurna",
      ashramName: "",
      address: "Venkatapur, Hospet Taluka",
      mobile: ["9449870231"],
      cropDiversity: "Navara Rice, Mangoes, Banana, desi cow milk",
    },
    {
      slNo: 194,
      name: "Yerriswamy",
      ashramName: "Panchatantra Gurukulam yogavidyashrama",
      address: "Tirumalakoppa, Hubballi-581207",
      mobile: ["9343401878"],
      cropDiversity: "50",
    },
    {
      slNo: 195,
      name: "R G ತಿಮ್ಮಪುರ",
      ashramName: "",
      address: "ಹಳ್ಳಿಗೋರಿ, ಹಲ್ಯಾಳ ರಸ್ತೆ, ಧಾರವಾಡ",
      mobile: ["9448907803"],
      cropDiversity: "ವಿವೇದ ತರಹದ ಹಣ್ಣುಗಳು",
    },
    {
      slNo: 196,
      name: "Dr B F Hulagur",
      ashramName: "",
      address: "Flat# 313 Vaastu Hill view 1 Rajarajeswari nagar, Bengaluru 560098",
      mobile: ["9632254884"],
      cropDiversity: "Kharif season: green gram, lablab, horse gram, groundnut, coriander, maize, onion chillies, brinjal, tomatoes, carrot, reddish etc as inter crops Rabi season: Rabi jowar, Bengal gram sesamum as inter crops and sole crop, safflower, sunflower, maize, vegetables like cucumber, ridge gourds, bottle gourds pumpkins etc. as hedge crops and intercrops, trees/fruits like neem, tamarind, acacia, shami, pongamia, hebbevu etc on the field bunds and field borders",
    },
    {
      slNo: 197,
      name: "Harsha D N",
      ashramName: "",
      address: "170/1, Dinka kaval, Chinakurali Hobli, Pandavapura taluk, Mandya District",
      mobile: ["9945951194"],
      cropDiversity: "ತೆಂಗು, ಅಡಿಕೆ, ತರಕಾರಿ, ಬಾಳೆ ಇತ್ಯಾದಿ",
    },
    {
      slNo: 198,
      name: "ಲಲಿತಾಂಬ",
      ashramName: "",
      address: "Singena agrahara, Anekal (TQ) Bengaluru (district)",
      mobile: ["8217649536"],
      cropDiversity: "ಹಲಸು, ನುಗ್ಗೆ, ಮಾವು, ಔಷಧೀಯ ಸಸ್ಯಗಳೂ",
    },
    {
      slNo: 199,
      name: "Harish Kumar NS",
      ashramName: "",
      address: "s/o Nanda Kumar SL Santhehalli (V & P), Malur (T), Kolar (D)-563130",
      mobile: ["7892862984"],
      cropDiversity: "All season fruits",
    },
    {
      slNo: 200,
      name: "ಮಹಾದೇವಿ ಬಸವರಾಜ ದೊಡ್ಡಮನಿ",
      ashramName: "",
      address: "ಹುಲಗಿನಕಟ್ಟೆ, ಕಲಘಟಗಿ ತಾಲೂಕು, ಧಾರವಾಡ ಜಿಲ್ಲಾ",
      mobile: ["9741253214"],
      cropDiversity: "ಮಡಕಿ, ಹುದ್ದು, ಹೆಸರು, ಅಗಸೆ, ಮಾವು, ಪಪ್ಪಾಯಿ, ಪೇರಲ, ಹನುಮಫಲ ಕಡಲೆ, ಅಡಿಕೆ, ತೆಂಗು ಎಲೆ, ಬಾಳೆ, ಕರಿಬೇವು, ಮುಂತಾದವು ಹಾಗೂ 20 ವಿಧದ ಹೂಗಳು ಮತ್ತು ಜೇನು ಕೂಡ ಇದೆ",
    },
    {
      slNo: 201,
      name: "ಎಂ ಎನ್ ಮಹೇಶ್ ಕುಮಾರ್",
      ashramName: "",
      address: "ಎಂ ವಿ ನಾರಾಯಣಪೇಟೆ, ಮಳವಳ್ಳಿ ತಾಲೂಕು, ಮಂಡ್ಯ ಜಿಲ್ಲೆ",
      mobile: ["9448273445"],
      cropDiversity: "ಸಪೋಟ, ತೆಂಗು, ಅಡಿಕೆ, ಕಾಫಿ, ಮೆಣಸು, ಏಲಕ್ಕಿ, ಹರಿಶಿಣ, ಬೋವಿನ ಬೆಳೆಗಳು ಮತ್ತು ಮನೆಗೆ ಆಗುವಷ್ಟು ಹಣ್ಣಿನ ಗಿಡಗಳು",
    },
    {
      slNo: 202,
      name: "ASHOK KUMAR G M",
      ashramName: "",
      address: "Donehally, (p) Jagalur, (t) Davanagere (d) 577528",
      mobile: ["9986480403"],
      cropDiversity: "Kokkanet arek Apple gavoa jura star grout etc",
    },
    {
      slNo: 203,
      name: "ವಿನೋದ ನಾರಾಯಣ",
      ashramName: "GANGA NARAYANA Farm",
      address: "Bellighati village, Bellighatti to Tadas road, Next to Girivana Farm",
      mobile: ["9449835936"],
      cropDiversity: "Chaew, Areca, ಲವಂಗ coconut, jaikai, dalchini, sandle Butter fruit, fruits (all types) Ayurveda plants",
    },
    {
      slNo: 204,
      name: "ಭೀಮಾನಂದ್ ಚೌಗಲಾ",
      ashramName: "ಧರಿತ್ರಿ ಕೃಷಿ ಆಶ್ರಮ",
      address: "ನಾಗಲಾವಿ ರಸ್ತೆ",
      mobile: ["9686453581"],
      cropDiversity: "ಗೋವಿನ ಜೋಳ್, ಕೆಂಪು ಹುರಳಿ, ನಿಂಬೆ ಹಣ್ಣು, ವಿವಿಧ ಪೆರು, ಅವಕೋಡ್, ಡಾಲಚಿನ್ನಿ, lemangrass, ತುಳಸಿ, ಯಾಲಕ್ಕಿ, ವಿವಿಧ ಗೆಣಸು, ವಿವಿಧ ಕಾಯಿಪಲ್ಲೇ, ಮಲ್ಲಿಗೆ, ತೊಂಡೆಕಾಯಿ, ರಾಜಮುಡಿ ಬತ್ತ, ಕರಿ ಬತ್ತ, ಬೆಳಗಾಂಬ ಬಾಸಾಮತಿ, ವಿವಿಧ ಅರಿಶಿನ, ಶ್ರೀಗಂಧ, ರಕ್ತ ಚಂದನ್, ಬಿದಿರು, ಬೋವು, ಗ್ಲಿರಿಸಿದೆಯಾ, ಕೌಳಿ, ಹಲಸು, ಸುಬಾಬಲಿ, ಗೂಡಂಬಿ, ಮಾವು, ನೆಲ್ಲಿಕಾಯಿ, ನೇರಳೆ, ಹತ್ತಿ ಗಿಡ, ಅಂಜುರ, ಬಾರಿ ಹಣ್ಣು, ಇನ್ನು ವಿವಿಧವುಗಳು",
    },
    {
      slNo: 205,
      name: "Satishraddi p radder",
      ashramName: "sri basav gopal natural farms",
      address: "kundur",
      mobile: ["8904874441"],
      cropDiversity: "Moringa sugarcane lime lemon anjur teak coconut",
    },
    {
      slNo: 206,
      name: "ಸುನಿಲ್ ಕುಮಾರ್ k n",
      ashramName: "ಪ್ರಕೃತಿ ಸಾವಯವ ತೋಟ",
      address: "ತೋಟದ ಮನೆ, ಕೆಂಕೆರೆ @(p), ಹುಳಿಯಾರ್ (h) ಚಿಕ್ಕನಾಯಕನಹಳ್ಳಿ (t) ತುಮಕೂರ್ (d) ಪಿನ್ ಕೋಡ್:-572218",
      mobile: ["6360192694"],
      cropDiversity: "ತೆಂಗು, ಅಡಿಕೆ, ಬಾಳೆ, ಮಾವು, ಹಲಸು, ಪರಂಗಿ, ನುಗ್ಗೆ, ಟೊಮೊಟೊ, ಮೆಣಸಿನಕಾಯಿ, ಬದನೇಕಾಯಿ ತೊಂಡೆಕಾಯಿ, ಚೆಂಡು ಹೂವುಗಳು, ಕಲ್ಲುಮೊಗ್ಗು, ರಾಗಿ, ತೊಗರಿ, ಹವರೆ, ಹಲಸಂಡೆ, cucumbar, ಹರಿಶಿನ, ಸಿಹಿಗೆಣಸು, ಮರೆಗೆಣಸು, ಹೆಬೆವು, ಮಹಾಗಣಿ, ಬಿದಿರು-ತಳಿಗಳು",
    },
    {
      slNo: 207,
      name: "Saraswathi",
      ashramName: "",
      address: "Channarayapatna, hassan, housing board",
      mobile: ["9902621246"],
      cropDiversity: "Tengu, adke, banana",
    },
    {
      slNo: 208,
      name: "Devaraja k v",
      ashramName: "",
      address: "Kurudi post, kurubarapalya Village, Gowribidanur TQ, chikkaballpur dis",
      mobile: ["9739274311"],
      cropDiversity: "Banana crops multi crop",
    },
    {
      slNo: 209,
      name: "Nagaraj mc",
      ashramName: "",
      address: "s/o bm chanabasapa Medikeranahalli at post jagalur taluk Davangere district Karnataka -577553",
      mobile: ["9449815524"],
      cropDiversity: "Maize dragon fruit mango lemon",
    },
    {
      slNo: 210,
      name: "ರವಿ.ಬಿ.ಆರ್",
      ashramName: "",
      address: "ಉಪನ್ಯಾಸಕರು ನಾಗಸಂದ್ರ. ಕೆಜಿ ಟೆಂಪಲ್ ಅಂಚೆ. ಗುಬ್ಬಿ ತಾ. ತುಮಕೂರು ಜಿಲ್ಲೆ",
      mobile: ["8095371967"],
      cropDiversity: "ಇನ್ನು ಬೆಳೆಯಬೇಕು",
    },
    {
      slNo: 211,
      name: "Shivu Mohan T",
      ashramName: "",
      address: "Aralalusandra village Thungani post Kasabha ho kanakapura taluk Bangalore south district",
      mobile: ["9591948756"],
      cropDiversity: "Mango, coconut, jackfruit, teakwood, neem wood, some medicine plants etc",
    },
    {
      slNo: 212,
      name: "Arunkumar n shettar",
      ashramName: "",
      address: "Arunkumar N Shettar Bcom LLb CA",
      mobile: ["9448874072"],
      cropDiversity: "ತೆಂಗಿನ ಅಡಿಕೆ ಹಣ್ಣುಗಳ",
    },
    {
      slNo: 213,
      name: "ಗಿರೀಶ್ ಮೂಡಿಗೆರೆ",
      ashramName: "Basamma ಕೃಷಿ ಆಶ್ರಮ",
      address: "ಹೆಸಗಲ್",
      mobile: ["9449448797"],
      cropDiversity: "ನೇಪಿಯರ್ ಹುಲ್ಲು ಮತ್ತು ಸಾಮಾನ್ಯ ಹುಲ್ಲು",
    },
    {
      slNo: 214,
      name: "Krishna Naik DG",
      ashramName: "",
      address: "Doddathandya village shivanahalli post kanakapura talok",
      mobile: ["8317424233"],
      cropDiversity: "Raagi thengu mavu",
    },
    {
      slNo: 215,
      name: "Vijay Kumar patil",
      ashramName: "",
      address: "At/post/-Andalagi Tq-Mundgod. Dust-karwar",
      mobile: ["9945602404"],
      cropDiversity: "Arecanut. Amla. Punarpuli. Billvaputri",
    },
  ];

  await Ashram.insertMany(ashrams);
  console.log("Ashrams seeded successfully!");
  mongoose.connection.close();
};

seedAshrams();
